# The `oteldemo` producer: the OpenTelemetry Demo (github.com/open-telemetry/opentelemetry-demo)
# at a pinned release tag, under its own Locust load generator, exporting through its own
# Collector into `otlp_in`. configs/oteldemo.yaml's header maps `logit.shape.*` onto OTLP's
# vocabulary; tools/shape-survey/oteldemo/ holds the two override files.
#
# The demo is shallow-cloned into the run directory at run time, never vendored, and the clone is
# checked against a pinned SHA because a tag can move.
#
# Representativeness and caveats: README "Producers" and "Caveats each author recorded". Every
# attribute comes from an OTel SDK, an instrumentation library, or a collector processor, with no
# operator-added context, so widths are a floor. The appended summary section names every
# collector processor, so a reader knows whose attributes are in the resource width.
#
# Environment: SHAPE_SURVEY_DURATION (main window, default 1200s), SHAPE_SURVEY_OTELDEMO_KEEP=1
# (the `resource: keep` second capture), SHAPE_SURVEY_OTELDEMO_KEEP_DURATION (default 180s).

#: The measured tag and its commit. A clone that lands on a different SHA fails the run.
SHAPE_SURVEY_OTELDEMO_TAG=3.1.0
SHAPE_SURVEY_OTELDEMO_SHA=dedc0178918e260823323b8d95005a8cb924b007

#: Capture window in seconds after the stack reports healthy. The load generator is steady from
#: its first cycle, so a short `SHAPE_SURVEY_DURATION` run is a smaller sample of the same thing.
SHAPE_SURVEY_OTELDEMO_DURATION_DEFAULT=1200

#: The demo's `.env` ships `DEMO_VERSION=latest`, which can move mid-capture; this pins it. This
#: and `OTEL_COLLECTOR_CONFIG_EXTRAS` are the only demo `.env` values this producer overrides.
SHAPE_SURVEY_OTELDEMO_IMAGE_TAG="${SHAPE_SURVEY_OTELDEMO_TAG}"

# Shallow-clones the pinned tag (~40 MB) into the run directory and checks the commit.
survey_oteldemo_fetch() {
    local dir="$1" sha
    echo "shape-survey: cloning opentelemetry-demo ${SHAPE_SURVEY_OTELDEMO_TAG} into ${dir}"
    git clone --quiet --depth 1 --branch "${SHAPE_SURVEY_OTELDEMO_TAG}" \
        https://github.com/open-telemetry/opentelemetry-demo.git "${dir}" ||
        survey_fail "could not clone opentelemetry-demo ${SHAPE_SURVEY_OTELDEMO_TAG}"
    sha="$(git -C "${dir}" rev-parse HEAD)"
    [ "${sha}" = "${SHAPE_SURVEY_OTELDEMO_SHA}" ] ||
        survey_fail "opentelemetry-demo ${SHAPE_SURVEY_OTELDEMO_TAG} is now ${sha}, not the pinned" \
            "${SHAPE_SURVEY_OTELDEMO_SHA}. A release tag moved: re-read the diff and update" \
            "SHAPE_SURVEY_OTELDEMO_SHA (and this producer's notes) rather than measuring a tree" \
            "the provenance misdescribes."

    # On an SELinux host the demo's bind mounts, which carry no `:z`, are denied inside their
    # containers and the collector never starts. Relabeling this run's own clone is the narrowest
    # fix: it touches nothing outside the run directory and needs no privilege.
    if command -v chcon >/dev/null 2>&1 && [ "$(getenforce 2>/dev/null || echo Disabled)" != "Disabled" ]; then
        chcon -R -t container_file_t "${dir}" ||
            echo "shape-survey: WARNING -- chcon failed on ${dir}; expect the demo's bind mounts" \
                "to be denied inside their containers" >&2
    fi
}

# This survey's overrides, as a second `--env-file`; the later file wins. Passing `--env-file` at
# all disables compose's automatic `.env` pickup, so the demo's own file is named explicitly first.
survey_oteldemo_env() {
    cat <<EOF
# Generated by tools/shape-survey/producers/oteldemo.sh -- layered over the demo's own .env.

# Pin the image tag: the demo ships DEMO_VERSION=latest, which can move mid-capture.
DEMO_VERSION=${SHAPE_SURVEY_OTELDEMO_IMAGE_TAG}

# The demo's documented collector extension point, which the core compose file loads last. See
# tools/shape-survey/oteldemo/otelcol-config-extras.yml.
OTEL_COLLECTOR_CONFIG_EXTRAS=${ROOT}/tools/shape-survey/oteldemo/otelcol-config-extras.yml

# Read by compose-overlay.yaml, so the overlay never hard-codes lib.sh's naming scheme.
SHAPE_SURVEY_NET=${SURVEY_NET}
EOF
}

# The stack, through `survey_compose`, whose already-running guard matters here: the demo fixes
# every `container_name` and its network name, so only one can exist on a host.
#
# `compose.yaml` alone, the demo's "core/minimal" layer: it has every application service and the
# load generator, so the SDK coverage is complete. `compose.full.yaml` adds only the Kafka group,
# and `compose.observability.yaml` adds backends that store telemetry rather than emit it, at
# several GB of RAM.
survey_oteldemo_compose() {
    survey_compose stack \
        -f "${SURVEY_RUN_DIR}/opentelemetry-demo/compose.yaml" \
        -f "${ROOT}/tools/shape-survey/oteldemo/compose-overlay.yaml" \
        --env-file "${SURVEY_RUN_DIR}/opentelemetry-demo/.env" \
        --env-file "${SURVEY_RUN_DIR}/survey.env" -- "$@"
}

# Readiness, in two parts. A healthy load generator means the application chain is up, but it
# doesn't depend on the collector, so it goes healthy while the collector crash-loops; the
# collector's own state is checked too (`running`, not `restarting`).
survey_oteldemo_ready() {
    survey_oteldemo_service_state load-generator health = healthy &&
        survey_oteldemo_service_state otel-collector state = running
}

# `<service> health|state = <expected>`: compares one compose service's container state. Health
# and state are separate lookups because `{{.State.Health.Status}}` renders empty on a container
# with no healthcheck.
survey_oteldemo_service_state() {
    local service="$1" what="$2" _eq="$3" expected="$4" cid format
    case "${what}" in
    health) format='{{.State.Health.Status}}' ;;
    state) format='{{.State.Status}}' ;;
    *) survey_fail "survey_oteldemo_service_state: unknown field '${what}'" ;;
    esac
    cid="$(survey_oteldemo_compose ps -q "${service}" 2>/dev/null || true)"
    [ -n "${cid}" ] || return 1
    [ "$(${DOCKER} inspect --format "${format}" "${cid}" 2>/dev/null || true)" = "${expected}" ]
}

# The producer's own summary.md section, written into the run directory and computed from
# summary.json alone.
survey_oteldemo_section_py() {
    cat <<'PYEOF'
#!/usr/bin/env python3
"""Renders the `oteldemo` producer's section of summary.md from /out/summary.json.

Per-event series carry `shape`'s `signal` tag, so the three signals separate inside one `otlp_in`;
per-batch series carry none (a (Resource, Scope) group can hold any mix), so they're reported once.
"""

import json
import pathlib

SUMMARY = json.loads(pathlib.Path("/out/summary.json").read_text())

#: Collector processors per pipeline at the measured tag, from the demo's
#: src/otel-collector/otelcol-config.yml `service.pipelines`. Update it when the tag moves.
PROCESSORS = {
    "traces": [
        "resource_detection",
        "memory_limiter",
        "transform/sanitize_spans",
        "gen_ai_normalizer",
        "transform/redact_sensitive_data",
        "redaction",
    ],
    "metrics": ["resource_detection", "memory_limiter"],
    "logs": ["resource_detection", "memory_limiter", "transform/sanitize_logs"],
}

#: Receivers per pipeline. Most metric points come from collector-side receivers, not an SDK.
RECEIVERS = {
    "traces": ["otlp"],
    "metrics": [
        "http_check/frontend-proxy",
        "host_metrics",
        "nginx",
        "otlp",
        "redis",
        "postgresql",
        "prometheus/ad",
        "span_metrics (connector)",
        "~~docker_stats~~ (removed, see below)",
    ],
    "logs": ["otlp"],
}


def rows(section, metric=None):
    for row in SUMMARY.get(section) or []:
        if metric is None or row.get("metric") == metric:
            yield row


def by_signal(metric, section="distributions"):
    return {r["signal"]: r for r in rows(section, metric)}


def hist(stats):
    return {int(k): v for k, v in (stats.get("histogram") or {}).items()}


def fraction_above(stats, n):
    h = hist(stats)
    total = sum(h.values())
    return sum(c for v, c in h.items() if v > n) / total if total else None


def num(value):
    if value is None:
        return "n/a"
    return f"{value:.0f}" if float(value).is_integer() else f"{value:.2f}"


def pct(value):
    return "n/a" if value is None else f"{value:.1%}"


def table(histogram, limit=14):
    """A value->count table as `n x count` cells, longest tail folded into a final cell."""
    items = sorted(histogram.items())
    head = items[:limit]
    cells = ", ".join(f"{v}&nbsp;x&nbsp;{c}" for v, c in head)
    if len(items) > limit:
        rest = sum(c for _, c in items[limit:])
        cells += f", (&gt;{head[-1][0]})&nbsp;x&nbsp;{rest}"
    return cells or "-"


def dist_row(label, row):
    if not row:
        return f"| {label} | 0 | n/a | n/a | n/a | n/a |"
    s = row["stats"]
    return (
        f"| {label} | {s['count']} | {num(s['p50'])} | {num(s['p90'])} |"
        f" {num(s['p99'])} | {num(s['max'])} |"
    )


out = []

# ---- where in the chain this sits ----------------------------------------------------------------
out.append("## OTLP after a collector: what these numbers include")
out.append("")
out.append(
    "Data reaches `logit` **after** the demo's own OpenTelemetry Collector, not straight from the"
    " SDKs. The chain is `SDK -> (OTLP/gRPC) -> otel-collector -> (OTLP/HTTP) -> otlp_in -> shape`,"
    " and the collector's processors have already run. At the measured tag those are, per pipeline:"
)
out.append("")
out.append("| pipeline | receivers | processors (in order) |")
out.append("|---|---|---|")
for pipeline in ("traces", "metrics", "logs"):
    out.append(
        f"| `{pipeline}` | {', '.join('`' + r + '`' for r in RECEIVERS[pipeline])} |"
        f" {', '.join('`' + p + '`' for p in PROCESSORS[pipeline])} |"
    )
out.append("")
out.append(
    "**`resource_detection` is the one that moves a number in this summary.** It runs on all three"
    " pipelines with `detectors: [env, docker, system]` and a long `resource_attributes` allow-list"
    " (`host.arch`, `host.cpu.vendor.id`, `host.cpu.family`, `host.cpu.model.id`,"
    " `host.cpu.model.name`, `host.cpu.stepping`, `host.cpu.cache.l2.size`, `os.description`, plus"
    " the detectors' defaults), so **every** resource-attribute count reported below is the SDK's"
    " own resource *plus* that block. An operator whose collector does not run"
    " `resource_detection`, or runs it with fewer attributes enabled, will see a narrower resource;"
    " one who also runs `k8sattributes` (not present here -- this is compose, not Kubernetes) will"
    " see a wider one."
)
out.append("")
out.append(
    "The other processors are near-neutral for shape: `memory_limiter` changes nothing,"
    " `transform/sanitize_spans` rewrites span *names*, `transform/sanitize_logs` renames one scope"
    " attribute, `gen_ai_normalizer` only touches GenAI spans (the agentic layer is not running"
    " here), and `transform/redact_sensitive_data` + `redaction` delete `demo.payment.card_cvv` and"
    " swap `user.email` for `user.hash` on the few spans that carry them -- a one-for-one swap and"
    " one deletion, not a width change worth a caveat."
)
out.append("")
out.append(
    "**`docker_stats` is the one receiver removed**, and it is forced rather than chosen: on an"
    " SELinux-enforcing host it cannot connect to `/var/run/docker.sock` at all, and a receiver"
    " that fails to start takes the whole collector down with it. Everything else in the demo's"
    " collector -- every other receiver, every processor, every exporter, all three pipelines --"
    " is exactly as shipped, with one `otlphttp` exporter added alongside. What the removal costs"
    " these numbers is `container.*` metrics about the demo's own containers: collector"
    " infrastructure telemetry, not application SDK output."
)
out.append("")
out.append(
    "**A minority of the metric points here came from an application SDK.** The metrics pipeline's"
    " receiver list above is mostly collector-side scrapers (`host_metrics` especially, which"
    " produces a large, wide-ish block of `system.*` points every interval) plus the `span_metrics`"
    " connector's derived series. Only the `otlp` receiver's share is SDK output. The traces and"
    " logs pipelines have no such dilution -- their only receiver is `otlp`."
)
out.append("")
out.append(
    "**There is no `batch` processor in any pipeline at this tag** (the core config's pipelines are"
    " listed above in full). So `logit.shape.batch.events` is not a collector re-batching window:"
    " it is **one `(Resource, Scope)` group of one collector export request**. `otlp_in` bypasses"
    " the `BatchAccumulator` and the OTLP codec never collapses groups -- every"
    " `(ResourceSpans/Metrics/Logs, Scope*)` pair inside one HTTP POST becomes its own `EventBatch`"
    " (`crates/logit-proto/src/otlp/mod.rs`). Read a batch here as *one resource's one"
    " instrumentation scope's share of one export request*, which is upstream of any `logit`-side"
    " grouping and downstream of whatever the SDK's own batch span processor decided."
)
out.append("")
out.append(
    "**No per-service breakdown.** `service.name` is a resource attribute and this tap runs"
    " `resource: drop`, so nothing below can be split by service. That is the deliberate trade:"
    " `resource: drop` is what lets a summary of this run leave the environment the traffic could"
    " not, and the count that matters for OTLP -- how *wide* a resource is -- survives it."
)
out.append("")

# ---- per signal ------------------------------------------------------------------------------------
counters = {(r["metric"], r["signal"]): r["total"] for r in rows("counters")}
events = {sig: total for (metric, sig), total in counters.items() if metric == "logit.shape.events"}
widths = {r["signal"]: r for r in rows("attribute_widths")}
signals = sorted(events, key=lambda s: -events[s])

out.append("## Per signal: attributes per event")
out.append("")
out.append(
    "`signal` is `shape`'s tag for what the observed event carried, `+`-joined when an event"
    " carried more than one. Attributes here are the **event's own** -- a span's span attributes, a"
    " metric point's point attributes, a log record's log attributes -- never the resource's."
)
out.append("")
out.append("| signal | events | p50 | p90 | p99 | max | >4 | >8 | >12 | >16 |")
out.append("|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|")
for sig in signals:
    row = widths.get(sig)
    if not row:
        continue
    s, f = row["stats"], row["fractions"]
    out.append(
        f"| `{sig}` | {s['count']} | {num(s['p50'])} | {num(s['p90'])} | {num(s['p99'])} |"
        f" {num(s['max'])} | {pct(f['>4'])} | {pct(f['>8'])} | {pct(f['>12'])} | {pct(f['>16'])} |"
    )
out.append("")
out.append("Exact value&rarr;count tables (the survey's real answer -- every N, not three percentiles):")
out.append("")
out.append("| signal | attributes per event |")
out.append("|---|---|")
for sig in signals:
    row = widths.get(sig)
    if row:
        out.append(f"| `{sig}` | {table(hist(row['stats']))} |")
out.append("")

# ---- spans -------------------------------------------------------------------------------------
out.append("## Spans: events, links, and span-event attributes")
out.append("")
out.append(
    "Per span, from the spans in the capture. A span event's own attributes are a separate"
    " population from the span's -- one value per span event, not per span."
)
out.append("")
out.append("| series | values | p50 | p90 | p99 | max |")
out.append("|---|--:|--:|--:|--:|--:|")
for metric, label in (
    ("logit.shape.span_events", "events per span"),
    ("logit.shape.span_links", "links per span"),
    ("logit.shape.span_event_attributes", "attributes per span event"),
):
    for sig, row in sorted(by_signal(metric).items()):
        out.append(dist_row(f"{label} (`{sig}`)", row))
for metric, label in (
    ("logit.shape.span_events", "events per span"),
    ("logit.shape.span_links", "links per span"),
    ("logit.shape.span_event_attributes", "attributes per span event"),
):
    for sig, row in sorted(by_signal(metric).items()):
        h = hist(row["stats"])
        if h:
            out.append("")
            out.append(f"`{metric}` (`{sig}`): {table(h)}")
out.append("")

# ---- nesting -----------------------------------------------------------------------------------
out.append("## Nesting: maps inside attribute values")
out.append("")
out.append(
    "`nested_maps` is how many of an event's attribute values are maps, `nested_map_width` how many"
    " entries each such map has, and `value_depth` the deepest nesting reached. OTLP's `AnyValue`"
    " can carry a `KvlistValue` at any depth, so this is the one wire format in the survey where"
    " deep nesting is cheap to produce -- what the SDKs actually do with that is the measurement."
)
out.append("")
out.append("| series | signal | values | p50 | p90 | p99 | max | value&rarr;count |")
out.append("|---|---|--:|--:|--:|--:|--:|---|")
for metric in (
    "logit.shape.nested_maps",
    "logit.shape.nested_map_width",
    "logit.shape.value_depth",
):
    for sig, row in sorted(by_signal(metric).items()):
        s = row["stats"]
        out.append(
            f"| `{metric.split('.')[-1]}` | `{sig}` | {s['count']} | {num(s['p50'])} |"
            f" {num(s['p90'])} | {num(s['p99'])} | {num(s['max'])} | {table(hist(s), limit=8)} |"
        )
out.append("")

# ---- bytes -------------------------------------------------------------------------------------
out.append("## Key and value byte lengths, and log bodies")
out.append("")
out.append(
    "`key_bytes` is an attribute *key*'s length and `value_bytes` a leaf string/bytes value's --"
    " the two numbers an interned-key or inline-string decision turns on. `body_bytes` is a log"
    " record's body."
)
out.append("")
out.append("| series | signal | values | p50 | p90 | p99 | max |")
out.append("|---|---|--:|--:|--:|--:|--:|")
for metric in ("logit.shape.key_bytes", "logit.shape.value_bytes", "logit.shape.body_bytes"):
    for sig, row in sorted(by_signal(metric).items()):
        # `dist_row`'s label is two cells here -- metric and signal -- so it lines up with the
        # seven-column header above.
        out.append(dist_row(f"`{metric.split('.')[-1]}` | `{sig}`", row))
out.append("")

# ---- value type mix ------------------------------------------------------------------------------
out.append("## Value-type mix")
out.append("")
out.append(
    "Counts of leaf values by model type, as a share of that signal's leaves -- `logit.shape.values.*`"
    " are counters, not distributions. OTLP's `AnyValue` maps onto `Value` directly, so this is as"
    " close as the survey gets to 'what types does real OTLP carry'."
)
out.append("")
TYPES = ["string", "int", "float", "bool", "bytes", "array", "map", "null", "timestamp"]
out.append("| signal | leaves | " + " | ".join(TYPES) + " |")
out.append("|---|--:|" + "--:|" * len(TYPES))
for sig in signals:
    counts = {t: counters.get((f"logit.shape.values.{t}", sig), 0) or 0 for t in TYPES}
    total = sum(counts.values())
    if not total:
        continue
    cells = " | ".join(pct(counts[t] / total) for t in TYPES)
    out.append(f"| `{sig}` | {total:.0f} | {cells} |")
out.append("")

# ---- per batch -----------------------------------------------------------------------------------
out.append("## Per batch: a (Resource, Scope) group of one collector export request")
out.append("")
out.append(
    "These carry no `signal` tag -- a batch is a `(Resource, Scope)` group and `shape` emits its"
    " per-batch measurements at `flush`, where no single signal applies. `batch.keysets` is how many"
    " distinct top-level attribute key-sets the events in one batch had between them."
)
out.append("")
out.append("| series | batches | p50 | p90 | p99 | max | value&rarr;count |")
out.append("|---|--:|--:|--:|--:|--:|---|")
for metric, label in (
    ("logit.shape.batch.events", "events per batch"),
    ("logit.shape.batch.resource_attributes", "resource attributes per batch"),
    ("logit.shape.batch.scope_attributes", "scope attributes per batch"),
    ("logit.shape.batch.keysets", "key-sets per batch"),
):
    for row in rows("distributions", metric):
        s = row["stats"]
        out.append(
            f"| {label} | {s['count']} | {num(s['p50'])} | {num(s['p90'])} | {num(s['p99'])} |"
            f" {num(s['max'])} | {table(hist(s), limit=10)} |"
        )
out.append("")

# ---- cumulative ------------------------------------------------------------------------------------
out.append("## Cumulative, since process start")
out.append("")
out.append(
    "One tap, so one set of tracking tables, covering all three signals together: `distinct_keys`"
    " is distinct **top-level attribute keys** and `distinct_keysets` distinct key-*sets*, with"
    " `top1`/`top5` the share of events carried by the most common one and five. `tracking_overflow`"
    " at `1` means a cap was hit and the two counts are floors."
)
out.append("")
gauges = {(g["tap"], g["metric"]): g["value"] for g in rows("gauges")}
taps = sorted({g["tap"] for g in rows("gauges")})
out.append("| tap | distinct keys | distinct key-sets | top1 share | top5 share | overflow |")
out.append("|---|--:|--:|--:|--:|--:|")
for tap in taps:
    out.append(
        f"| `{tap}` | {num(gauges.get((tap, 'logit.shape.distinct_keys')))} |"
        f" {num(gauges.get((tap, 'logit.shape.distinct_keysets')))} |"
        f" {pct(gauges.get((tap, 'logit.shape.keyset_share.top1')))} |"
        f" {pct(gauges.get((tap, 'logit.shape.keyset_share.top5')))} |"
        f" {num(gauges.get((tap, 'logit.shape.tracking_overflow')))} |"
    )
out.append("")
out.append(
    "**These are a demo application's numbers.** Every instrumentation the demo ships is on at"
    " once, the workload is one synthetic Locust generator walking fixed journeys, and no operator"
    " context (team, environment, tenant, owner) has been added anywhere -- which is exactly what a"
    " real deployment adds and this one does not. Treat the widths as a floor over SDK output, not"
    " as a typical."
)
out.append("")

pathlib.Path("/out/section.md").write_text("\n".join(out) + "\n")
print("oteldemo: wrote /out/section.md")
PYEOF
}

# ---- the optional `resource: keep` second run ----------------------------------------------------
#
# Off unless `SHAPE_SURVEY_OTELDEMO_KEEP=1`; see README "`resource: keep` captures". Its output is
# identity-bearing, so it writes only to `resource-keep/` and nothing from it joins the main
# summary.
#
# It retargets `SURVEY_RUN_DIR` for its duration: `start_logit`, `stop_logit`, and
# `survey_summarize` all read that one variable. The window is short because it holds the whole
# ~20-container stack up, and a starved shared host can stretch wall-clock time well past it.
SHAPE_SURVEY_OTELDEMO_KEEP_DURATION_DEFAULT=180

# Per-service medians, which summarize.py's series key can't separate. It walks shape.log with
# summarize.py's own `parse_attrs`, which is under `--self-test` for a keep line's bare arrays.
survey_oteldemo_keep_section_py() {
    cat <<'PYEOF'
#!/usr/bin/env python3
"""Per-service attribute-count medians from a `resource: keep` capture.

Reads /out/shape.log directly, because summary.json has already pooled every service. It imports
summarize.py's `parse_attrs` rather than a second parser that could disagree with it.

Its output NAMES SERVICES and stays in this run directory.
"""

import importlib.util
import pathlib
import statistics
from collections import defaultdict

spec = importlib.util.spec_from_file_location("summarize", "/tools/summarize.py")
summarize = importlib.util.module_from_spec(spec)
spec.loader.exec_module(summarize)

# (metric, signal, service) -> samples
buckets: defaultdict[tuple[str, str, str], list[float]] = defaultdict(list)
tags: dict[str, str] = {}
for raw in pathlib.Path("/out/shape.log").read_text().splitlines():
    if not raw or not raw.startswith(" "):
        tags = {}
        continue
    line = raw.strip()
    if line.startswith("attrs "):
        tags = summarize.parse_attrs(line[len("attrs ") :].strip())
        continue
    if not line.startswith("metric "):
        continue
    name, _, rendered = line[len("metric ") :].strip().partition(" ")
    if not name.startswith("logit.shape.") or not rendered.startswith("samples=["):
        continue
    values = rendered[len("samples=[") : rendered.index("]")]
    if not values:
        continue
    key = (name, tags.get("signal", ""), tags.get("service.name", "(no service.name)"))
    buckets[key].extend(float(v) for v in values.split(","))


def rows(metric):
    return sorted(
        ((sig, svc, vals) for (m, sig, svc), vals in buckets.items() if m == metric),
        key=lambda r: (r[0], -len(r[2])),
    )


out = ["# `oteldemo`, `resource: keep`: per-service attribute counts", ""]
out.append(
    "**This file names services, and is the output of a capture that deliberately let resource"
    " identity through.** It is not part of the main run's summary and does not travel with it."
    " See tools/shape-survey/configs/oteldemo-keep.yaml's header."
)
out.append("")
out.append(
    "`logit.shape.attributes` is the count of an event's **own** attributes -- a span's span"
    " attributes, a metric point's point attributes, a log record's log attributes. The resource's"
    " own width is not in this number; it is `logit.shape.batch.resource_attributes`, which a"
    " `flush`-time series cannot carry a resource on and so stays pooled."
)
out.append("")
out.append("| signal | service | events | median | p90 | max |")
out.append("|---|---|--:|--:|--:|--:|")
for sig, svc, vals in rows("logit.shape.attributes"):
    ordered = sorted(vals)
    p90 = ordered[max(0, round(0.9 * len(ordered)) - 1)] if len(ordered) >= 10 else None
    out.append(
        f"| `{sig}` | `{svc}` | {len(vals)} | {statistics.median(ordered):.0f} |"
        f" {'n/a' if p90 is None else f'{p90:.0f}'} | {max(ordered):.0f} |"
    )
out.append("")

pathlib.Path("/out/per-service.md").write_text("\n".join(out) + "\n")
print("oteldemo: wrote /out/per-service.md")
PYEOF
}

survey_oteldemo_keep_run() {
    local main_dir="${SURVEY_RUN_DIR}" keep_dir duration
    keep_dir="${main_dir}/resource-keep"
    duration="${SHAPE_SURVEY_OTELDEMO_KEEP_DURATION:-${SHAPE_SURVEY_OTELDEMO_KEEP_DURATION_DEFAULT}}"
    mkdir -p "${keep_dir}"
    # As in `survey_out_dir`: the container's `logit` user has an unrelated uid.
    chmod 777 "${keep_dir}"

    echo "shape-survey: second capture, resource: keep, into ${keep_dir} (${duration}s)"
    SURVEY_RUN_DIR="${keep_dir}"
    survey_provenance oteldemo \
        "OpenTelemetry Demo ${SHAPE_SURVEY_OTELDEMO_TAG}, resource: keep -- IDENTITY-BEARING per-service run, stays in the run directory; see the main capture one level up for the survey's own numbers"
    {
        echo "second run: configs/oteldemo-keep.yaml (resource: keep), same demo stack, ${duration}s"
        echo "purpose: per-service attribute-count medians, which resource: drop cannot produce"
        echo "WARNING: this capture carries service.name, host.name, container.id and everything"
        echo "  else the collector's resource_detection stamped. It does not leave this directory."
    } >>"${keep_dir}/provenance.txt"

    start_logit "${ROOT}/tools/shape-survey/configs/oteldemo-keep.yaml"
    survey_capture_for "${duration}"
    stop_logit

    # The ordinary pooled summary, then the per-service table only a keep capture can produce.
    survey_summarize >/dev/null
    survey_oteldemo_keep_section_py >"${keep_dir}/per-service.py"
    survey_python keep-section -- python3 /out/per-service.py

    SURVEY_RUN_DIR="${main_dir}"
}

survey_oteldemo() {
    local run_dir config duration demo

    survey_out_dir oteldemo
    run_dir="${SURVEY_RUN_DIR}"
    config="${ROOT}/tools/shape-survey/configs/oteldemo.yaml"
    duration="${SHAPE_SURVEY_DURATION:-${SHAPE_SURVEY_OTELDEMO_DURATION_DEFAULT}}"
    demo="${run_dir}/opentelemetry-demo"

    survey_provenance oteldemo \
        "OpenTelemetry Demo ${SHAPE_SURVEY_OTELDEMO_TAG}: real SDK auto-instrumentation in ~10 languages under a synthetic load generator, via the demo's own collector -- a demo app: every instrumentation enabled at once, no operator-added context, no production enrichment"

    survey_oteldemo_fetch "${demo}"
    survey_oteldemo_env >"${run_dir}/survey.env"

    {
        echo "opentelemetry-demo tag: ${SHAPE_SURVEY_OTELDEMO_TAG}"
        echo "opentelemetry-demo commit: $(git -C "${demo}" rev-parse HEAD)"
        echo "collector image: $(grep -E '^COLLECTOR_CONTRIB_IMAGE=' "${demo}/.env" | cut -d= -f2-)"
        echo "demo image tag: ${SHAPE_SURVEY_OTELDEMO_IMAGE_TAG} (.env ships DEMO_VERSION=latest; pinned here)"
        echo "compose files: compose.yaml (the demo's own core/minimal layer) +"
        echo "  tools/shape-survey/oteldemo/compose-overlay.yaml"
        echo "  NOT compose.full.yaml (adds only the Kafka group) and NOT compose.observability.yaml"
        echo "  (adds Jaeger/Prometheus/Grafana/OpenSearch/OpAMP -- backends that store telemetry"
        echo "  rather than emit it, and several GB of RAM to measure nothing extra)."
        echo "collector config: the demo's own src/otel-collector/otelcol-config.yml, UNCHANGED."
        echo "  One otlphttp exporter is added through the demo's own documented extension point"
        echo "  (OTEL_COLLECTOR_CONFIG_EXTRAS -> tools/shape-survey/oteldemo/otelcol-config-extras.yml),"
        echo "  alongside the demo's own exporters on all three of its traces/metrics/logs"
        echo "  pipelines. No receiver, processor or pipeline is otherwise altered."
        echo "collector pipelines at this tag (what 'after the collector' means for these numbers):"
        echo "  traces:  otlp -> resource_detection, memory_limiter, transform/sanitize_spans,"
        echo "           gen_ai_normalizer, transform/redact_sensitive_data, redaction"
        echo "  metrics: docker_stats, http_check/frontend-proxy, host_metrics, nginx, otlp, redis,"
        echo "           postgresql, prometheus/ad, span_metrics -> resource_detection, memory_limiter"
        echo "  logs:    otlp -> resource_detection, memory_limiter, transform/sanitize_logs"
        echo "  There is NO \`batch\` processor in any of them at this tag."
        echo "docker_stats: NOT captured, and the ONE deviation from the demo's own pipelines."
        echo "  The receiver cannot start on an SELinux-enforcing host -- 'permission denied while"
        echo "  trying to connect to the docker API at unix:///var/run/docker.sock' -- and a failed"
        echo "  receiver start takes the whole collector down, so this is the difference between a"
        echo "  capture and no capture, not one missing metric family. It is removed from the"
        echo "  metrics pipeline's receiver list in the extras layer; every other receiver,"
        echo "  processor and exporter is exactly as the demo ships them. What is lost is"
        echo "  \`container.*\` metrics about the demo's own containers -- collector infrastructure"
        echo "  telemetry, not application SDK output. Making it work would mean relabelling the"
        echo "  host's /var/run/docker.sock or running the collector privileged, which is more"
        echo "  than a survey should ask of a shared daemon."
        echo "languages instrumented in the core layer: Java (ad), .NET (cart), Go (checkout,"
        echo "  product-catalog, flagd), C++ (currency), Ruby (email), TypeScript (frontend,"
        echo "  flagd-ui), JavaScript (payment), Python (recommendation, load-generator), PHP"
        echo "  (quote), Rust (shipping), plus Envoy (frontend-proxy) and nginx (image-provider)."
        echo "duration: ${duration}s of capture after the load generator reported healthy"
        echo "config: tools/shape-survey/configs/oteldemo.yaml (one otlp_in, one shape tap)"
    } >>"${run_dir}/provenance.txt"

    # logit first: the collector's retry queue is finite, so nothing is lost while ~20 containers
    # come up.
    start_logit "${config}"

    echo "shape-survey: bringing up the demo's core stack (this pulls ~20 images on a cold daemon)"
    survey_oteldemo_compose up -d --no-build --pull missing ||
        survey_fail "the opentelemetry-demo core stack did not come up"

    # Allows for a cold start with ~20 image pulls.
    survey_capture_until survey_oteldemo_ready 900

    survey_capture_for "${duration}"

    # An export failure to `logit` shows up only in the collector's log, so take it before the check
    # below, which points at it.
    survey_oteldemo_compose logs --no-color --tail 2000 otel-collector \
        >"${run_dir}/service-otel-collector.log" 2>&1 || true

    # Every measurement arrives through the collector, and a bad config or blocked mount can take
    # it down after readiness. A mid-window restart is a gap the summary wouldn't otherwise show.
    survey_oteldemo_service_state otel-collector state = running ||
        survey_fail "the demo's otel-collector is not running at the end of the capture --" \
            "see service-otel-collector.log in the run directory; every measurement in this" \
            "survey arrives through it, so a summary built on this window would be a gap"

    stop_logit

    # summary.json first; then this producer's own reading of it, appended to summary.md.
    survey_summarize >/dev/null
    survey_oteldemo_section_py >"${run_dir}/section.py"
    survey_python section -- python3 /out/section.py
    survey_summarize --append section.md

    # After the main capture is summarized, while the stack is still up. A failure here warns
    # rather than exits, so a completed main capture doesn't read as failed. `SURVEY_RUN_DIR` is
    # restored because the keep run retargets it and an early exit would leave it pointing at the
    # subdirectory.
    if [ -n "${SHAPE_SURVEY_OTELDEMO_KEEP:-}" ]; then
        survey_oteldemo_keep_run || {
            SURVEY_RUN_DIR="${run_dir}"
            echo "shape-survey: WARNING -- the resource: keep second capture failed." \
                "The main capture in ${run_dir} is complete and unaffected; see" \
                "${run_dir}/resource-keep/ for how far the second one got." >&2
            true
        }
    fi
}
