#!/bin/bash
# Usage: script/audit
# Supply-chain checks: the license/ban policy in deny.toml, and known vulnerabilities across the
# dependency graph.

set -e
SCRIPT_PATH="$(dirname -- "$(readlink -f -- "${0}")")"
source "${SCRIPT_PATH}/common.sh"

if ! in_project_environment; then
    run ./script/audit "$@"
    exit
fi

cargo deny check
cargo audit
