//! `collectd_in -> collectd_out` round trip over real UDP sockets. The components run in-process
//! (a `CollectdOutput` sending to a bound, live `CollectdInput`), not through `logit run`. This
//! lives in `logit-cli` because it already depends on both `logit-inputs` and `logit-outputs`; a
//! dev-dependency between those two crates would be a cycle.
//!
//! This file proves the real sockets and components compose to the codec's fixed point. The
//! codec's own correctness is fixed-pointed and proptested in
//! `crates/logit-proto/tests/collectd_fixed_point.rs`. The fixed point is the one ADR
//! `lossless-transit` requires, modulo the numbered list in [`logit_proto::collectd`]'s module doc
//! (`crates/logit-proto/src/collectd/mod.rs`, "Permitted normalizations"), which is the canonical
//! copy; the tables below cite its numbers. ADR `collectd-binary-relay` numbers the same list one
//! higher from its (3) on, because it splits (3) in two.
//!
//! ## Fixture corpus (`tests/fixtures/collectd/`)
//!
//! One file pair per byte-for-byte case: `<name>.in` (a raw collectd datagram) and
//! `<name>.expected` (the datagram `collectd_out` must emit for that decode, or the marker
//! [`SAME_AS_INPUT`] when the sink reproduces the input verbatim). The decode-only cases and
//! `repacked-at-1024` have an `.in` only.
//!
//! The files are binary, so every `.in` is also built in code by [`build_in`]'s [`PacketBuilder`],
//! which is independent of `logit_proto::collectd::part`'s writers so a fixture tests the codec
//! against the protocol rather than against itself.
//! [`every_committed_in_file_matches_its_builder`] pins the committed bytes to the builder: read
//! [`build_in`] to see what a fixture is. Each `.expected` was generated by this harness and
//! reviewed as a hex dump, part by part, against the normalization list.
//!
//! The three `testdata/interop/collectd/*.raw` captures from a real Debian `collectd` aren't
//! copied here; `crates/logit-inputs/src/collectd.rs`'s `interop_fixture_*` tests replay them in
//! place. [`a_real_collectd_capture_grows_when_its_elided_time_parts_are_restored`] reads one of
//! them to pin what normalization 10 costs: a real sender elides unchanged `TimeHR`/`IntervalHR`
//! parts, `collectd_out` restates them on every list, and the 1296-byte `collectd-000.raw` relays
//! as 1717 bytes in two datagrams.
//!
//! ## Per-fixture normalizations
//!
//! Byte-for-byte cases: the captured datagram equals `.expected`, and the live decode equals the
//! original decode as a whole `EventBatch`.
//!
//! | Fixture | Normalizations | What it pins |
//! |---|---|---|
//! | `single-gauge` | none ([`SAME_AS_INPUT`]) | the baseline: one GAUGE list, `f64` little-endian, full identity, exact `TimeHR`/`IntervalHR` |
//! | `legacy-time-interval` | **1** | a second-resolution `Time`(0x0001)/`Interval`(0x0007) pair re-emitted as `TimeHR`(0x0008)/`IntervalHR`(0x0009) |
//! | `multi-value-load` | none ([`SAME_AS_INPUT`]) | a 3-data-source list is one event with three records in wire order, re-emitted as one list, not three |
//! | `if-octets-derive` | none ([`SAME_AS_INPUT`]) | a negative DERIVE (`i64`, big-endian) survives the `f64` model round trip |
//! | `counter-and-absolute` | none ([`SAME_AS_INPUT`]) | a `u64::MAX` COUNTER (see [`build_in`]) beside an ABSOLUTE |
//! | `elided-identity` | **3** | three lists differing only in `TypeInstance`; the sender's elision and the encoder's recomputed elision agree, so it stays [`SAME_AS_INPUT`] |
//! | `elided-time-interval` | **10** | two lists stating `TimeHR`/`IntervalHR` once, as a real sender does; the `.expected` restates both on the second list, +24 B |
//! | `empty-instances` | **3** | empty `PluginInstance`/`TypeInstance` parts (a sender clearing an instance) decode to absent attributes and are elided on egress |
//! | `no-interval` | **9** | two lists with no interval part; the `.expected` gains `IntervalHR 0` (collectd's "unspecified") on each, +24 B |
//! | `non-utf8-host` | none ([`SAME_AS_INPUT`]) | a `0xFF` in `Host` decodes to `Value::Bytes` and is re-emitted verbatim |
//! | `unknown-and-signature-parts` | **5** | an unknown `0x00FF` part and a `0x0200` Signature part between two lists: skipped by length, dropped on egress, and the list behind them still decodes |
//! | `nan-gauge` | **6** | a non-canonical NaN payload (`0xFFF8_0000_0000_0001`) decodes to a `NO_RECORDED_VALUE`-flagged `Gauge(0.0)` and leaves as this platform's canonical `f64::NAN` |
//! | `sub-second-time` | **2** | a `cdtime_t` whose sub-second bits move one 2⁻³⁰ s tick on the first hop; the second hop is byte-identical to the first |
//! | `notification-failure`/`-warning`/`-okay` | none ([`SAME_AS_INPUT`]) | one notification each, severity 1/2/4: an `Event::log` with `collectd.severity` and `LogRecord::severity` `Error`/`Warn`/`Info`, no metrics |
//!
//! One case is one-way lossy, so it asserts the `.expected` wire bytes only:
//!
//! | Fixture | Normalizations | What it pins |
//! |---|---|---|
//! | `slash-in-plugin` | **8** | a `Plugin` of `mount/data` and a `TypeInstance` of `/var/log` leave as `mount_data` and `_var_log` (collectd's own `escape_slashes`), counted `logit.output.identity.sanitized{reason="substituted"}` |
//!
//! One structural case, where the bytes are allowed to move:
//!
//! | Fixture | Normalizations | What it pins |
//! |---|---|---|
//! | `repacked-at-1024` | **3**, **9** | 30 lists in one 1412-byte input with no interval part, re-packed under a 1024-byte cap: ≥2 datagrams, none over the cap, whole-batch equality. No `.expected`, since the boundaries may move; `no-interval` pins the `IntervalHR 0` bytes |
//!
//! One multi-datagram case, whose `.in` and `.expected` each concatenate several datagrams
//! (built by [`notification_between_lists_datagrams`] and decoded one at a time, as a listener
//! receives them), with its own test:
//!
//! | Fixture | Normalizations | What it pins |
//! |---|---|---|
//! | `notification-between-lists` | **11** | list (`type_instance=free`), notification, list (no `type_instance`), decoded from three datagrams into one batch and relayed: the notification gets its own datagram, and the second list restates Host/Plugin/Type in full, neither eliding against the notification's identity nor inheriting the first list's `type_instance` |
//!
//! Decode-only cases, sent to the live `collectd_in` and asserted on the delivered events and the
//! [`Registry`]'s diagnostic counters:
//!
//! | Fixture | Diagnostic | What it pins |
//! |---|---|---|
//! | `encrypted` | `encrypted_packet_dropped` | a `0x0210` Encryption part stops the walk: the list before it is kept, the list behind it never decodes |
//! | `no-time` | none | normalization **7**: no `Time`/`TimeHR` part stamps `received_at` |
//! | `truncated-values` | `bad_part` | a `Values` header declaring more bytes than the datagram holds abandons the rest and keeps what was already decoded |
//! | `incomplete-identity` | `incomplete_identity` | an empty `Host` part clears the sticky host, and the list behind it is skipped, as collectd's own receiver does |
//!
//! ## What this corpus does *not* cover
//!
//! ADR `lossless-transit` reads "no fixture" as "not covered", so:
//!
//! - **Normalization 4 (list reordering within a batch)** has no fixture because this pair never
//!   reorders. `CollectdEncoder::encode_into` emits lists in `EventBatch::events` order, and
//!   `crates/logit-proto/tests/collectd_fixed_point.rs`'s `decode(encode(b)) == b` compares an
//!   ordered `Vec<Event>`. The entry licenses a downstream reorder (a `Fanout`, a buffered sink
//!   retry).
//!
//! ## Cross-protocol
//!
//! `statsd_in -> collectd_out` exercises the encoder's fallback path (no `collectd.*` identity),
//! including its two likeliest drops: a sampled counter's non-integral extrapolation, and a
//! DogStatsD tag, which collectd has no wire form for. `collectd_in -> aggregate -> collectd_out`
//! pins that a cumulative `Sum` (what COUNTER and DERIVE decode to) passes through `aggregate`
//! untouched, so the relay stays byte-identical with a window in the middle.

use bytes::Bytes;
use logit_core::{Diagnostics, EventBatch, MetricKind, Registry, Resource, Value};
use logit_inputs::collectd::CollectdInput;
use logit_inputs::statsd::StatsdInput;
use logit_outputs::collectd::CollectdOutput;
use logit_pipeline::{Delivered, Fanout, Input, Output};
use logit_proto::collectd::{
    CollectdDecoder, CollectdEncoder, ATTR_HOST, ATTR_PLUGIN, ATTR_PLUGIN_INSTANCE, ATTR_TYPE,
    ATTR_TYPE_INSTANCE, DEFAULT_MAX_PACKET_BYTES,
};
use logit_proto::Decoder;
use logit_transforms::Aggregator;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;
use tokio::net::UdpSocket;
use tokio::sync::mpsc;

/// The `.expected` marker meaning "byte-identical to the `.in` file", shared with the other
/// round-trip corpora.
const SAME_AS_INPUT: &[u8] = b"== SAME AS INPUT ==";

// -- the wire, written by hand -------------------------------------------------------------------
//
// Independent of `logit_proto::collectd::part`'s writers (see the module doc), which also can't
// write the legacy and malformed shapes this corpus needs.

const TYPE_HOST: u16 = 0x0000;
const TYPE_TIME: u16 = 0x0001;
const TYPE_PLUGIN: u16 = 0x0002;
const TYPE_PLUGIN_INSTANCE: u16 = 0x0003;
const TYPE_TYPE: u16 = 0x0004;
const TYPE_TYPE_INSTANCE: u16 = 0x0005;
const TYPE_VALUES: u16 = 0x0006;
const TYPE_INTERVAL: u16 = 0x0007;
const TYPE_TIME_HR: u16 = 0x0008;
const TYPE_INTERVAL_HR: u16 = 0x0009;
const TYPE_MESSAGE: u16 = 0x0100;
const TYPE_SEVERITY: u16 = 0x0101;
const TYPE_SIGNATURE: u16 = 0x0200;
const TYPE_ENCRYPTION: u16 = 0x0210;
/// A part type no collectd defines -- normalization 5's "unknown part types are skipped by length."
const TYPE_FROM_THE_FUTURE: u16 = 0x00FF;

/// Bytes of a numeric part: the four-byte header plus one `u64` BE.
const NUMBER_PART_LEN: usize = 12;

const DS_COUNTER: u8 = 0;
const DS_GAUGE: u8 = 1;
const DS_DERIVE: u8 = 2;
const DS_ABSOLUTE: u8 = 3;

/// `2023-11-14T22:13:20Z` in whole seconds, the instant every fixture in this corpus is stamped
/// with -- far enough from "now" that a receipt-time fallback (normalization 7) is unmistakable.
const TIME_SECONDS: u64 = 1_700_000_000;
/// [`TIME_SECONDS`] as a `cdtime_t`.
const TIME_HR: u64 = TIME_SECONDS << 30;
/// A ten-second `Interval`, as a `cdtime_t`.
const INTERVAL_HR: u64 = 10 << 30;
/// The sub-second half of `sub-second-time`'s `TimeHR`. Most tick values survive
/// `cdtime → ns → cdtime` untouched and would exercise nothing; this one moves by one tick on the
/// first hop, which [`a_sub_second_time_moves_at_most_one_tick_and_is_then_stable`] asserts.
const SUB_SECOND_TICKS: u64 = 0x1234_567E;

#[derive(Default)]
struct PacketBuilder {
    bytes: Vec<u8>,
}

impl PacketBuilder {
    fn new() -> Self {
        Self::default()
    }

    /// `type: u16 BE, len: u16 BE` (the length *including* these four bytes), then the payload.
    fn part(mut self, part_type: u16, payload: &[u8]) -> Self {
        let len = (4 + payload.len()) as u16;
        self.bytes.extend_from_slice(&part_type.to_be_bytes());
        self.bytes.extend_from_slice(&len.to_be_bytes());
        self.bytes.extend_from_slice(payload);
        self
    }

    /// A NUL-terminated string part. An empty `value` is the five-byte part a sender writes to
    /// *clear* a sticky field, which is not the same as omitting the part.
    fn string(self, part_type: u16, value: &[u8]) -> Self {
        let mut payload = value.to_vec();
        payload.push(0);
        self.part(part_type, &payload)
    }

    /// A `u64`-BE numeric part.
    fn number(self, part_type: u16, value: u64) -> Self {
        self.part(part_type, &value.to_be_bytes())
    }

    /// A Values part: the `u16` data-source count, then every type byte, then every eight-byte
    /// value -- two vectors, not interleaved pairs.
    fn values(self, values: &[(u8, [u8; 8])]) -> Self {
        let mut payload = Vec::new();
        payload.extend_from_slice(&(values.len() as u16).to_be_bytes());
        for (ds_type, _) in values {
            payload.push(*ds_type);
        }
        for (_, raw) in values {
            payload.extend_from_slice(raw);
        }
        self.part(TYPE_VALUES, &payload)
    }

    /// Raw bytes with no framing at all -- for the malformed tail
    /// `truncated-values` ends in.
    fn raw(mut self, bytes: &[u8]) -> Self {
        self.bytes.extend_from_slice(bytes);
        self
    }

    fn build(self) -> Vec<u8> {
        self.bytes
    }
}

fn gauge(value: f64) -> (u8, [u8; 8]) {
    // Little-endian, unlike every other value type on this wire -- collectd writes `htole64` for
    // gauges specifically.
    (DS_GAUGE, value.to_le_bytes())
}

/// A GAUGE carrying an exact NaN *bit pattern*, which `f64::to_le_bytes` could not be trusted to
/// preserve through a `f64` literal.
fn gauge_bits(bits: u64) -> (u8, [u8; 8]) {
    (DS_GAUGE, bits.to_le_bytes())
}

fn counter(value: u64) -> (u8, [u8; 8]) {
    (DS_COUNTER, value.to_be_bytes())
}

fn derive(value: i64) -> (u8, [u8; 8]) {
    (DS_DERIVE, value.to_be_bytes())
}

fn absolute(value: u64) -> (u8, [u8; 8]) {
    (DS_ABSOLUTE, value.to_be_bytes())
}

/// Every `.in` file in the corpus, as the bytes a real sender would write.
///
/// Part order is collectd's `add_to_buffer` order (Host, Time, Interval, Plugin, PluginInstance,
/// Type, TypeInstance, Values), which is also `collectd_out`'s, so a fixture that exercises no
/// normalization stays [`SAME_AS_INPUT`].
fn build_in(name: &str) -> Vec<u8> {
    match name {
        // -- byte for byte ---------------------------------------------------------------------
        "single-gauge" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"used")
            .values(&[gauge(1.5)])
            .build(),

        // The legacy second-resolution pair: no modern collectd writes it, but every one accepts
        // it. Re-emitted as TimeHR/IntervalHR (normalization 1).
        "legacy-time-interval" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME, TIME_SECONDS)
            .number(TYPE_INTERVAL, 10)
            .string(TYPE_PLUGIN, b"cpu")
            .string(TYPE_PLUGIN_INSTANCE, b"0")
            .string(TYPE_TYPE, b"cpu")
            .string(TYPE_TYPE_INSTANCE, b"user")
            .values(&[derive(12_345)])
            .build(),

        // `load`'s three data sources: one Values part, one event with three records in wire
        // order, and one Values part on the way out.
        "multi-value-load" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .values(&[gauge(0.05), gauge(0.15), gauge(0.25)])
            .build(),

        // Both values stay inside 2^53, where an `i64` is exact as an `f64`. Above it the model's
        // int/double collapse moves the value, a documented gap (`docs/known-gaps.md`).
        "if-octets-derive" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"interface")
            .string(TYPE_PLUGIN_INSTANCE, b"eth0")
            .string(TYPE_TYPE, b"if_octets")
            .values(&[derive(1_234_567_890_123), derive(-42)])
            .build(),

        // `u64::MAX` decodes to the `f64` 2^64 (the nearest double). It survives only because
        // `as_u64`'s upper bound is inclusive and the `as` cast saturates.
        "counter-and-absolute" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"disk")
            .string(TYPE_PLUGIN_INSTANCE, b"sda")
            .string(TYPE_TYPE, b"disk_ops")
            .values(&[counter(u64::MAX), absolute(17)])
            .build(),

        // Three lists sharing one identity, only `TypeInstance` changing: the protocol's
        // compression scheme. TimeHR/IntervalHR are restated per list so normalization 10 doesn't
        // apply.
        "elided-identity" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"cpu")
            .string(TYPE_PLUGIN_INSTANCE, b"0")
            .string(TYPE_TYPE, b"cpu")
            .string(TYPE_TYPE_INSTANCE, b"user")
            .values(&[derive(100)])
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_TYPE_INSTANCE, b"system")
            .values(&[derive(50)])
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_TYPE_INSTANCE, b"idle")
            .values(&[derive(900)])
            .build(),

        // `TimeHR`/`IntervalHR` stated once and inherited by the second list, as a real collectd
        // writes them. Normalization 10: the `.expected` restates both, 24 bytes larger.
        "elided-time-interval" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"cpu")
            .string(TYPE_PLUGIN_INSTANCE, b"0")
            .string(TYPE_TYPE, b"cpu")
            .string(TYPE_TYPE_INSTANCE, b"user")
            .values(&[derive(100)])
            .string(TYPE_TYPE_INSTANCE, b"system")
            .values(&[derive(50)])
            .build(),

        // Two five-byte string parts carrying nothing but their NUL: how a sender *clears* a
        // sticky instance it set earlier in the same datagram.
        "empty-instances" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"df")
            .string(TYPE_PLUGIN_INSTANCE, b"")
            .string(TYPE_TYPE, b"df_complex")
            .string(TYPE_TYPE_INSTANCE, b"")
            .values(&[gauge(1024.0)])
            .build(),

        // No interval part, as collectd's `network` plugin sends when a list's interval matches
        // the daemon's default. Normalization 9: the `.expected` gains `IntervalHR 0` on each list.
        // `TimeHR` is restated on the second list so normalization 10 doesn't apply too.
        "no-interval" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"used")
            .values(&[gauge(1.5)])
            .number(TYPE_TIME_HR, TIME_HR)
            .string(TYPE_TYPE_INSTANCE, b"free")
            .values(&[gauge(2.5)])
            .build(),

        // Normalization 8's substitution, reachable from a real decode. collectd's own receiver
        // runs `escape_slashes` over a raw path (a `df` plugin instance, a mount point); this codec
        // does it on egress instead, and counts it. One-way, so wire bytes only.
        "slash-in-plugin" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"mount/data")
            .string(TYPE_TYPE, b"df_complex")
            .string(TYPE_TYPE_INSTANCE, b"/var/log")
            .values(&[gauge(7.0)])
            .build(),

        // collectd's strings are bytes, so a host name from a non-UTF-8 locale can arrive.
        "non-utf8-host" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-\xff-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"free")
            .values(&[gauge(2.5)])
            .build(),

        // An unknown part type, and a `SecurityLevel Sign` sender's Signature part (an HMAC-SHA256
        // over the plaintext that follows, then the username).
        "unknown-and-signature-parts" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"swap")
            .string(TYPE_TYPE, b"swap")
            .string(TYPE_TYPE_INSTANCE, b"used")
            .values(&[gauge(100.0)])
            .part(TYPE_FROM_THE_FUTURE, b"a part type this codec has never heard of")
            .part(TYPE_SIGNATURE, &{
                let mut payload = vec![0xABu8; 32];
                payload.extend_from_slice(b"fixture-user");
                payload
            })
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_TYPE_INSTANCE, b"free")
            .values(&[gauge(200.0)])
            .build(),

        // A negative quiet NaN with a payload bit set: collectd's "no value this interval", in a
        // bit pattern other than this platform's `f64::NAN`.
        "nan-gauge" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"sensors")
            .string(TYPE_PLUGIN_INSTANCE, b"coretemp")
            .string(TYPE_TYPE, b"temperature")
            .string(TYPE_TYPE_INSTANCE, b"core0")
            .values(&[gauge_bits(0xFFF8_0000_0000_0001)])
            .build(),

        // Live low bits reach normalization 2; a whole-second TimeHR can never move.
        "sub-second-time" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR | SUB_SECOND_TICKS)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"processes")
            .string(TYPE_TYPE, b"ps_state")
            .string(TYPE_TYPE_INSTANCE, b"running")
            .values(&[gauge(42.0)])
            .build(),

        // 30 lists in one datagram under collectd's 1452-byte default. They carry no interval
        // part only so all 30 fit. The sink re-packs them at 1024.
        "repacked-at-1024" => {
            let mut builder = PacketBuilder::new()
                .string(TYPE_HOST, b"web-1")
                .number(TYPE_TIME_HR, TIME_HR)
                .string(TYPE_PLUGIN, b"cpu")
                .string(TYPE_PLUGIN_INSTANCE, b"0")
                .string(TYPE_TYPE, b"cpu");
            for index in 0..30u64 {
                if index > 0 {
                    builder = builder.number(TYPE_TIME_HR, TIME_HR);
                }
                builder = builder
                    .string(TYPE_TYPE_INSTANCE, format!("state-{index:02}-of-30").as_bytes())
                    .values(&[derive(index as i64 * 1000)]);
            }
            builder.build()
        }

        // -- notifications -----------------------------------------------------------------------
        //
        // Wire order: TimeHR, Severity, Host, Plugin, Type, Message, collectd's sender order
        // (`logit_proto::collectd::encode`'s `write_notification`). No PluginInstance/TypeInstance:
        // `write_notification` omits both when empty, matching decode's "absent" reading, so the
        // round trip needs no normalization.
        "notification-failure" => PacketBuilder::new()
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_SEVERITY, 1)
            .string(TYPE_HOST, b"web-1")
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .string(TYPE_MESSAGE, b"load average critical")
            .build(),

        "notification-warning" => PacketBuilder::new()
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_SEVERITY, 2)
            .string(TYPE_HOST, b"web-1")
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .string(TYPE_MESSAGE, b"load average high")
            .build(),

        "notification-okay" => PacketBuilder::new()
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_SEVERITY, 4)
            .string(TYPE_HOST, b"web-1")
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .string(TYPE_MESSAGE, b"load average back to normal")
            .build(),

        // Three datagrams concatenated; see [`notification_between_lists_datagrams`].
        "notification-between-lists" => notification_between_lists_datagrams().concat(),

        // -- decode only -------------------------------------------------------------------------

        // The second list is ciphertext to this codec and must never decode.
        "encrypted" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"uptime")
            .string(TYPE_TYPE, b"uptime")
            .values(&[gauge(3600.0)])
            .part(TYPE_ENCRYPTION, &[0x5A; 48])
            .values(&[gauge(7200.0)])
            .build(),

        // No Time part of either resolution: normalization 7's receipt-time stamp.
        "no-time" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"cached")
            .values(&[gauge(512.0)])
            .build(),

        // A Values header declaring 24 bytes with six left in the datagram: a packet cut mid-part
        // by a sender, a middlebox, or a hostile length.
        "truncated-values" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .values(&[gauge(0.5)])
            .raw(&[0x00, 0x06, 0x00, 0x18, 0x00, 0x02])
            .build(),

        // An empty Host part clears the sticky host, so the list behind it has no identity;
        // collectd's own receiver rejects that with `-EINVAL`.
        "incomplete-identity" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .values(&[gauge(0.5)])
            .string(TYPE_HOST, b"")
            .values(&[gauge(0.9)])
            .build(),

        other => panic!("no builder for fixture {other:?}"),
    }
}

/// The byte-for-byte cases, in the module doc's first table's order.
const BYTE_FOR_BYTE: &[&str] = &[
    "single-gauge",
    "legacy-time-interval",
    "multi-value-load",
    "if-octets-derive",
    "counter-and-absolute",
    "elided-identity",
    "elided-time-interval",
    "empty-instances",
    "no-interval",
    "non-utf8-host",
    "unknown-and-signature-parts",
    "nan-gauge",
    "sub-second-time",
    "notification-failure",
    "notification-warning",
    "notification-okay",
];

/// The one-way-lossy case: wire bytes asserted, decode equality not.
const ONE_WAY: &[&str] = &["slash-in-plugin"];

/// The structural case: an `.in` and no `.expected`.
const STRUCTURAL: &[&str] = &["repacked-at-1024"];

/// The decode-only cases: an `.in` each, asserted on delivered events and diagnostics.
const DECODE_ONLY: &[&str] = &["encrypted", "no-time", "truncated-values", "incomplete-identity"];

/// The multi-datagram case. It has its own test because [`assert_byte_for_byte`] expects one
/// captured datagram per case.
const MULTI_DATAGRAM: &[&str] = &["notification-between-lists"];

/// Every `.in` file this corpus commits.
fn in_fixtures() -> impl Iterator<Item = &'static str> {
    BYTE_FOR_BYTE
        .iter()
        .chain(ONE_WAY)
        .chain(STRUCTURAL)
        .chain(DECODE_ONLY)
        .chain(MULTI_DATAGRAM)
        .copied()
}

/// The three datagrams `notification-between-lists` concatenates. They must be built and decoded
/// separately: collectd's sender never packs a notification with a value list
/// (`testdata/interop/collectd/collectd-notification-000.raw` is one notification alone), so
/// "list, notification, list" is always three UDP sends.
///
/// Each carries full identity, so the `.expected` is byte-identical to the `.in`. The invariant:
/// a notification packed into a batch must not leave the encoder's elision state (`last`) behind,
/// or the third list would elide its Host/Plugin/Type against the notification's, or inherit the
/// first list's `type_instance`.
fn notification_between_lists_datagrams() -> Vec<Vec<u8>> {
    vec![
        // A value list, `type_instance=free`.
        PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"free")
            .values(&[gauge(512.0)])
            .build(),
        // A notification with no `TypeInstance`: never set in this datagram, not cleared.
        PacketBuilder::new()
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_SEVERITY, 2)
            .string(TYPE_HOST, b"web-1")
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_MESSAGE, b"low memory")
            .build(),
        // Another value list, same plugin/type as the first, no `TypeInstance`, with full
        // identity.
        PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .values(&[gauge(256.0)])
            .build(),
    ]
}

// -- corpus files ---------------------------------------------------------------------------------

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/collectd")
}

/// The recorded-capture directory, read in place rather than copied into this corpus.
fn testdata_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testdata/interop/collectd")
}

/// How many parts of type `part_type` a datagram carries, walking the part headers' `len`s. A
/// byte-pattern count would be wrong: a `0x0008` can appear inside a Values payload.
fn count_parts(datagram: &[u8], part_type: u16) -> usize {
    let mut at = 0usize;
    let mut count = 0usize;
    while at + 4 <= datagram.len() {
        let this = u16::from_be_bytes([datagram[at], datagram[at + 1]]);
        let len = u16::from_be_bytes([datagram[at + 2], datagram[at + 3]]) as usize;
        assert!(len >= 4 && at + len <= datagram.len(), "malformed part at {at}");
        if this == part_type {
            count += 1;
        }
        at += len;
    }
    assert_eq!(at, datagram.len(), "the datagram should end on a part boundary");
    count
}

fn read(path: &Path) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn read_fixture(name: &str, ext: &str) -> Vec<u8> {
    read(&fixtures_dir().join(format!("{name}.{ext}")))
}

/// The bytes a case's sink output must equal: either the literal `.expected` file, or (when that
/// file is [`SAME_AS_INPUT`]) the case's own `.in` bytes.
fn expected_bytes(name: &str, input: &[u8]) -> Vec<u8> {
    let expected = read_fixture(name, "expected");
    if expected.as_slice() == SAME_AS_INPUT {
        input.to_vec()
    } else {
        expected
    }
}

/// Every committed `.in` file must equal what [`build_in`] produces.
#[test]
fn every_committed_in_file_matches_its_builder() {
    for name in in_fixtures() {
        assert_eq!(
            read_fixture(name, "in"),
            build_in(name),
            "{name}.in has drifted from build_in()'s description of it"
        );
    }
}

// -- the harness ----------------------------------------------------------------------------------

fn direct_batch(raw: &[u8]) -> EventBatch {
    let mut decoder = CollectdDecoder::new(Arc::new(Resource::default()));
    decoder.decode(Bytes::copy_from_slice(raw)).expect("fixture should decode")
}

/// [`direct_batch`] for several datagrams: one decoder, one `decode_into` per datagram (each
/// resets the sticky state, as a listener's successive receives do), flattened into one
/// `EventBatch`, the shape a `BatchAccumulator` hands a sink.
fn direct_batch_multi(datagrams: &[Vec<u8>]) -> EventBatch {
    let resource = Arc::new(Resource::default());
    let mut decoder = CollectdDecoder::new(resource.clone());
    let mut events = Vec::new();
    for datagram in datagrams {
        decoder
            .decode_into(Bytes::copy_from_slice(datagram), 0, &mut events)
            .expect("fixture datagram should decode");
    }
    EventBatch { resource, scope: None, events }
}

/// A plain UDP capture socket (the raw-bytes half of each assertion) beside a bound, live
/// [`CollectdInput`] draining into a [`Fanout`] channel (the decoded-`EventBatch` half). The input
/// is bound, then `local_addr()` read, then spawned, so there is no bind-drop race.
///
/// Unlike the syslog and statsd harnesses, there's no `normalize_receipt_time`: every
/// byte-for-byte fixture carries a wire `Time`/`TimeHR`, so `Event::timestamp` is origin data and
/// compares equal. `no-time` is decode-only.
struct Harness {
    capture: UdpSocket,
    capture_addr: SocketAddr,
    input_addr: SocketAddr,
    rx: mpsc::Receiver<Delivered>,
}

/// How long to wait for a send's first datagram or batch, and then for each further one.
/// `SUBSEQUENT` bounds the "and nothing else came" assertions.
const FIRST: Duration = Duration::from_millis(500);
const SUBSEQUENT: Duration = Duration::from_millis(200);

impl Harness {
    async fn new() -> Self {
        let capture = UdpSocket::bind("127.0.0.1:0").await.expect("binding the capture socket");
        let capture_addr = capture.local_addr().expect("capture socket should have a local addr");

        let mut input = CollectdInput::new("127.0.0.1:0");
        input.bind().await.expect("binding the collectd_in listener");
        let input_addr = input.local_addr().expect("bind() should leave a real address behind");

        let (tx, rx) = mpsc::channel(64);
        let sink = Fanout::new(vec![tx]);
        tokio::spawn(async move {
            let _ = input.run(sink).await;
        });

        Self { capture, capture_addr, input_addr, rx }
    }

    /// A harness whose [`CollectdInput`] carries `diag`, for the decode-only cases.
    async fn with_diagnostics(diag: Diagnostics) -> Self {
        let capture = UdpSocket::bind("127.0.0.1:0").await.expect("binding the capture socket");
        let capture_addr = capture.local_addr().expect("capture socket should have a local addr");

        let mut input = CollectdInput::new("127.0.0.1:0").with_diagnostics(diag);
        input.bind().await.expect("binding the collectd_in listener");
        let input_addr = input.local_addr().expect("bind() should leave a real address behind");

        let (tx, rx) = mpsc::channel(64);
        let sink = Fanout::new(vec![tx]);
        tokio::spawn(async move {
            let _ = input.run(sink).await;
        });

        Self { capture, capture_addr, input_addr, rx }
    }

    /// Sends `batch` once to the capture socket and once to the live `collectd_in`, each through a
    /// fresh [`CollectdOutput`] passed through `configure` (a sink owns its socket, so it can't
    /// serve both legs), and returns every captured datagram and the decode.
    async fn round_trip_with(
        &mut self,
        batch: &EventBatch,
        configure: impl Fn(CollectdOutput) -> CollectdOutput,
    ) -> (Vec<Vec<u8>>, EventBatch) {
        let captured = self.capture_only(batch, &configure).await;

        let mut to_input = configure(CollectdOutput::udp(self.input_addr.to_string()).unwrap());
        to_input.send(batch).await.expect("send to the live collectd_in");
        (captured, self.drain_decoded().await)
    }

    /// [`Harness::round_trip_with`] with `collectd_out`'s defaults (`max_packet_bytes: 1452`, no
    /// `hostname:`).
    async fn round_trip(&mut self, batch: &EventBatch) -> (Vec<Vec<u8>>, EventBatch) {
        self.round_trip_with(batch, |sink| sink).await
    }

    /// Sends `batch` to the capture socket only, returning every datagram it received.
    async fn capture_only(
        &mut self,
        batch: &EventBatch,
        configure: impl Fn(CollectdOutput) -> CollectdOutput,
    ) -> Vec<Vec<u8>> {
        let mut to_capture = configure(CollectdOutput::udp(self.capture_addr.to_string()).unwrap());
        to_capture.send(batch).await.expect("send to the capture socket");
        self.drain_captured().await
    }

    /// Every datagram the capture socket holds: the first waited on for [`FIRST`], each later one
    /// for [`SUBSEQUENT`].
    async fn drain_captured(&mut self) -> Vec<Vec<u8>> {
        let mut buf = vec![0u8; 65_536];
        let mut datagrams = Vec::new();
        let mut wait = FIRST;
        while let Ok(result) = tokio::time::timeout(wait, self.capture.recv_from(&mut buf)).await {
            let (n, _) = result.expect("recv_from should succeed");
            datagrams.push(buf[..n].to_vec());
            wait = SUBSEQUENT;
        }
        assert!(!datagrams.is_empty(), "the capture socket received no datagram at all");
        datagrams
    }

    /// Every batch the live `collectd_in` delivered, merged into one: how a multi-datagram send is
    /// batched isn't this test's concern.
    async fn drain_decoded(&mut self) -> EventBatch {
        let mut batches = Vec::new();
        let mut wait = FIRST;
        while let Ok(delivered) = tokio::time::timeout(wait, self.rx.recv()).await {
            let delivered = delivered.expect("the Fanout channel should not have closed");
            batches.push(logit_pipeline::unwrap_batch(delivered));
            wait = SUBSEQUENT;
        }
        assert!(!batches.is_empty(), "collectd_in delivered nothing at all");
        let mut merged = batches.remove(0);
        for batch in batches {
            assert_eq!(batch.resource, merged.resource, "one decoder, one shared resource");
            assert!(batch.scope.is_none(), "collectd carries no scope concept");
            merged.events.extend(batch.events);
        }
        merged
    }

    /// Sends `raw` straight to the live `collectd_in`, for the decode-only cases: bytes no encoder
    /// would produce.
    async fn send_raw(&self, raw: &[u8]) {
        let sender =
            UdpSocket::bind("127.0.0.1:0").await.expect("binding an ephemeral sender socket");
        sender.send_to(raw, self.input_addr).await.expect("sending the raw datagram");
    }
}

/// Whether `registry` recorded a point named `metric` carrying `tag`. Drains, so call once.
fn counted(registry: &Registry, metric: &str, tag: (&str, &str)) -> bool {
    registry.drain(0).into_iter().any(|event| {
        event.metrics.iter().any(|m| logit_core::interner::resolve(m.name) == metric)
            && event.attributes.get(tag.0).and_then(Value::as_str) == Some(tag.1)
    })
}

/// The summed value of every point named `metric` carrying `tag` in `events`. Takes an
/// already-drained slice because `Registry::drain` empties the registry.
fn metric_sum(events: &[logit_core::Event], metric: &str, tag: (&str, &str)) -> f64 {
    events
        .iter()
        .filter(|e| e.attributes.get(tag.0).and_then(Value::as_str) == Some(tag.1))
        .flat_map(|e| &e.metrics)
        .filter(|m| logit_core::interner::resolve(m.name) == metric)
        .map(|m| match &m.kind {
            MetricKind::Sum(sum) => sum.value,
            other => panic!("{metric} must be a counter, got {other:?}"),
        })
        .sum()
}

fn attr(event: &logit_core::Event, key: &str) -> Option<Value> {
    event.attributes.get(key).cloned()
}

fn name_of(record: &logit_core::MetricRecord) -> &'static str {
    logit_core::interner::resolve(record.name)
}

// -- byte for byte ---------------------------------------------------------------------------------

/// Asserts one fixture relays as one datagram equal to its `.expected` bytes, and its live decode
/// equals its direct decode.
async fn assert_byte_for_byte(harness: &mut Harness, fixture: &str) {
    let raw = read_fixture(fixture, "in");
    let batch = direct_batch(&raw);
    let expected = expected_bytes(fixture, &raw);
    let (captured, decoded) = harness.round_trip(&batch).await;
    assert_eq!(
        captured.len(),
        1,
        "{fixture}: every byte-for-byte fixture fits one default-capped datagram"
    );
    assert_eq!(
        captured[0], expected,
        "{fixture}: raw datagram bytes should match .expected (modulo the module doc's permitted \
         normalizations)"
    );
    assert_eq!(
        decoded, batch,
        "{fixture}: decode(sink output) should equal the original decode, as a whole EventBatch"
    );
}

#[tokio::test]
async fn the_corpus_round_trips_byte_for_byte() {
    let mut harness = Harness::new().await;
    for fixture in BYTE_FOR_BYTE {
        assert_byte_for_byte(&mut harness, fixture).await;
    }
}

/// Normalization 8 ([`ONE_WAY`]): a `/` in an identity field becomes `_` and is counted. The far
/// end decodes the substituted identity, and the record name follows it.
#[tokio::test]
async fn a_slash_in_an_identity_field_is_substituted_counted_and_not_a_round_trip() {
    let raw = read_fixture("slash-in-plugin", "in");
    let batch = direct_batch(&raw);
    assert_eq!(
        attr(&batch.events[0], ATTR_PLUGIN),
        Some(Value::from("mount/data")),
        "the fixture's premise: the raw `/` survives decode untouched"
    );

    let registry = Registry::new();
    let telemetry = registry.telemetry_for("out", "collectd_out", "sink");
    let mut harness = Harness::new().await;
    let (captured, decoded) =
        harness.round_trip_with(&batch, |sink| sink.with_telemetry(telemetry.clone())).await;

    assert_eq!(captured.len(), 1);
    assert_eq!(captured[0], read_fixture("slash-in-plugin", "expected"));
    assert_ne!(captured[0], raw, "this fixture is one-way: the `/` does not survive");
    assert_eq!(attr(&decoded.events[0], ATTR_PLUGIN), Some(Value::from("mount_data")));
    assert_eq!(attr(&decoded.events[0], ATTR_TYPE_INSTANCE), Some(Value::from("_var_log")));
    assert_eq!(name_of(&decoded.events[0].metrics[0]), "mount_data.df_complex");

    // Three substituted bytes (one in `mount/data`, two in `/var/log`), but the counter is per
    // field, and each of the two sinks counts its own copy.
    let events = registry.drain(0);
    assert_eq!(
        metric_sum(&events, "logit.output.identity.sanitized", ("reason", "substituted")),
        4.0,
        "plugin and type_instance are each counted once per sink, over two sinks"
    );
}

/// Normalization 10: `TimeHR`/`IntervalHR` stated once come back on every list, 24 bytes larger,
/// and the decodes still compare equal.
#[tokio::test]
async fn elided_time_and_interval_parts_are_restored_per_list() {
    let raw = read_fixture("elided-time-interval", "in");
    let expected = read_fixture("elided-time-interval", "expected");
    assert_eq!(
        expected.len(),
        raw.len() + 2 * NUMBER_PART_LEN,
        "one restored TimeHR and one restored IntervalHR, both 12-byte numeric parts"
    );
    assert_eq!(count_parts(&raw, TYPE_TIME_HR), 1);
    assert_eq!(count_parts(&raw, TYPE_INTERVAL_HR), 1);
    assert_eq!(count_parts(&expected, TYPE_TIME_HR), 2, "one per value list on egress");
    assert_eq!(count_parts(&expected, TYPE_INTERVAL_HR), 2);

    // Also in `the_corpus_round_trips_byte_for_byte`; repeated so this test stands alone.
    let mut harness = Harness::new().await;
    assert_byte_for_byte(&mut harness, "elided-time-interval").await;
}

/// Normalization 10 on a real Debian `collectd`'s capture (`testdata/interop/collectd/`, read in
/// place): 26 value lists behind 17 `TimeHR` parts and one `IntervalHR`. Restoring the missing 35
/// turns one 1296-byte datagram into 1717 bytes across two. `docs/adr/collectd-binary-relay.md`
/// and `docs/deploying.md` quote these numbers, so they're pinned here.
#[tokio::test]
async fn a_real_collectd_capture_grows_when_its_elided_time_parts_are_restored() {
    let raw = read(&testdata_dir().join("collectd-000.raw"));
    assert_eq!(raw.len(), 1296);
    assert_eq!(count_parts(&raw, TYPE_VALUES), 26, "26 value lists");
    assert_eq!(count_parts(&raw, TYPE_TIME_HR), 17, "...behind 17 TimeHR parts");
    assert_eq!(count_parts(&raw, TYPE_INTERVAL_HR), 1, "...and a single IntervalHR");

    let batch = direct_batch(&raw);
    assert_eq!(batch.events.len(), 26);

    let mut harness = Harness::new().await;
    let (captured, decoded) = harness.round_trip(&batch).await;
    let total: usize = captured.iter().map(Vec::len).sum();
    assert_eq!(captured.len(), 2, "the restored parts push it past the 1452-byte default cap");
    assert_eq!(total, 1717, "1296 bytes in, 1717 out -- about 30% more, per normalization 10");
    for datagram in &captured {
        assert!(datagram.len() <= DEFAULT_MAX_PACKET_BYTES, "each datagram still fits the cap");
        assert_eq!(
            count_parts(datagram, TYPE_TIME_HR),
            count_parts(datagram, TYPE_VALUES),
            "one TimeHR per value list, which is the whole point"
        );
    }

    // Bytes grew; information didn't change.
    assert_eq!(decoded, batch, "every one of the 26 lists survives the relay unchanged");
}

/// A three-data-source `load` list is one event carrying three records in wire order, not three
/// events; that is what lets it re-emit as one Values part.
#[tokio::test]
async fn a_multi_data_source_list_stays_one_event_with_records_in_wire_order() {
    let raw = read_fixture("multi-value-load", "in");
    let batch = direct_batch(&raw);
    assert_eq!(batch.events.len(), 1, "one Values part is one event");
    let names: Vec<&str> = batch.events[0].metrics.iter().map(name_of).collect();
    assert_eq!(names, vec!["load.load.0", "load.load.1", "load.load.2"]);

    let mut harness = Harness::new().await;
    let (_, decoded) = harness.round_trip(&batch).await;
    assert_eq!(decoded.events.len(), 1);
    assert_eq!(
        decoded.events[0].metrics.iter().map(|m| m.kind.clone()).collect::<Vec<_>>(),
        vec![MetricKind::Gauge(0.05), MetricKind::Gauge(0.15), MetricKind::Gauge(0.25)],
        "the three gauges must come back in the order they went out"
    );
}

/// Normalization 6: a NaN gauge is a `NO_RECORDED_VALUE`-flagged `Gauge(0.0)` in the model, which
/// is what lets whole-`EventBatch` equality hold (`Gauge(f64::NAN)` never equals itself).
#[tokio::test]
async fn a_nan_gauge_is_a_flagged_point_on_both_sides_of_the_relay() {
    let raw = read_fixture("nan-gauge", "in");
    let batch = direct_batch(&raw);
    let record = &batch.events[0].metrics[0];
    assert_eq!(record.kind, MetricKind::Gauge(0.0));
    assert!(record.is_no_recorded_value(), "collectd's NaN is the model's NO_RECORDED_VALUE");

    let mut harness = Harness::new().await;
    let (captured, decoded) = harness.round_trip(&batch).await;
    // The re-emitted NaN is this platform's canonical one, not the input's payload bits.
    let value_bytes = &captured[0][captured[0].len() - 8..];
    assert_eq!(value_bytes, f64::NAN.to_le_bytes(), "the NaN payload bits canonicalize");
    assert_ne!(value_bytes, 0xFFF8_0000_0000_0001u64.to_le_bytes(), "...and are not the input's");
    assert!(decoded.events[0].metrics[0].is_no_recorded_value());
}

/// Normalization 2: a `cdtime_t` with live sub-second bits may move one tick on the first hop, and
/// the second hop must be byte-identical to the first.
#[tokio::test]
async fn a_sub_second_time_moves_at_most_one_tick_and_is_then_stable() {
    let raw = read_fixture("sub-second-time", "in");
    let batch = direct_batch(&raw);
    let mut harness = Harness::new().await;

    let (first, decoded_once) = harness.round_trip(&batch).await;
    assert_eq!(first[0], expected_bytes("sub-second-time", &raw));

    let (second, decoded_twice) = harness.round_trip(&decoded_once).await;
    assert_eq!(
        second[0], first[0],
        "the second hop must be byte-identical to the first -- a tick that kept drifting would not \
         be a permitted normalization, it would be a broken conversion"
    );
    assert_eq!(decoded_twice, decoded_once, "and the model side must be a fixed point too");

    // The one-tick tolerance itself: the `TimeHR` part's payload is the eight bytes after its
    // four-byte header, and this fixture writes it as the datagram's second part.
    let wire_time = |bytes: &[u8]| {
        let at = 4 + b"web-1".len() + 1 + 4; // Host part, then the TimeHR header.
        u64::from_be_bytes(bytes[at..at + 8].try_into().unwrap())
    };
    let original = TIME_HR | SUB_SECOND_TICKS;
    let moved = wire_time(&first[0]);
    assert!(
        moved.abs_diff(original) <= 1,
        "a TimeHR may move at most one 2^-30 s tick on the first hop, got {moved} from {original}"
    );
    assert_ne!(
        moved, original,
        "SUB_SECOND_TICKS is chosen precisely because it *does* move -- if this ever stops being \
         true the fixture has quietly stopped exercising normalization 2"
    );
}

/// Normalization 3's datagram boundaries: 30 lists from one 1412-byte datagram leave as several,
/// because the sink's `max_packet_bytes` decides where boundaries fall.
#[tokio::test]
async fn thirty_lists_in_one_datagram_repack_at_a_lower_cap() {
    let raw = read_fixture("repacked-at-1024", "in");
    assert!(
        raw.len() <= DEFAULT_MAX_PACKET_BYTES,
        "the input is one legal default-capped datagram"
    );
    let batch = direct_batch(&raw);
    assert_eq!(batch.events.len(), 30);

    let mut harness = Harness::new().await;
    let (captured, decoded) =
        harness.round_trip_with(&batch, |sink| sink.with_max_packet_bytes(1024)).await;

    assert!(
        captured.len() >= 2,
        "30 lists cannot fit one 1024-byte datagram, got {}",
        captured.len()
    );
    for (index, datagram) in captured.iter().enumerate() {
        assert!(
            datagram.len() <= 1024,
            "datagram {index} is {} bytes, over the configured cap",
            datagram.len()
        );
    }
    // A list that starts a fresh datagram restates its identity rather than eliding it across
    // the boundary.
    assert_eq!(
        decoded, batch,
        "the whole batch must survive re-packing, however the datagrams were cut"
    );
}

// -- multi-datagram: notifications --------------------------------------------------------------

/// Normalization 11: list, notification, list, decoded from three datagrams into one batch and
/// relayed. The notification gets its own datagram, and neither it nor the second list inherits
/// the first list's `type_instance` from the encoder's elision state.
#[tokio::test]
async fn a_notification_between_two_value_lists_is_its_own_datagram_and_the_next_list_restates_identity(
) {
    let datagrams = notification_between_lists_datagrams();
    let batch = direct_batch_multi(&datagrams);
    assert_eq!(batch.events.len(), 3);
    assert!(batch.events[0].log.is_none() && !batch.events[0].metrics.is_empty());
    assert!(batch.events[1].log.is_some() && batch.events[1].metrics.is_empty());
    assert!(batch.events[2].log.is_none() && !batch.events[2].metrics.is_empty());
    assert_eq!(attr(&batch.events[0], ATTR_TYPE_INSTANCE), Some(Value::from("free")));
    assert_eq!(attr(&batch.events[1], ATTR_TYPE_INSTANCE), None, "the notification never had one");
    assert_eq!(
        attr(&batch.events[2], ATTR_TYPE_INSTANCE),
        None,
        "the second list never had one either"
    );

    let mut harness = Harness::new().await;
    let (captured, decoded) = harness.round_trip(&batch).await;

    assert_eq!(captured.len(), 3, "the notification forces a flush on both sides of it");
    let expected_concat = read_fixture("notification-between-lists", "expected");
    let mut at = 0usize;
    for (index, expected_piece) in datagrams.iter().enumerate() {
        let piece = &expected_concat[at..at + expected_piece.len()];
        assert_eq!(
            &captured[index], piece,
            "datagram {index} did not match the committed .expected slice"
        );
        at += expected_piece.len();
    }
    assert_eq!(
        at,
        expected_concat.len(),
        "the .expected file must be exactly these three datagrams, back to back"
    );

    // The second list restates Host/Plugin/Type in full, and `TypeInstance` stays absent on it and
    // on the notification, never inherited as "free" from the first list.
    assert_eq!(count_parts(&captured[2], TYPE_HOST), 1, "the second list must restate Host");
    assert_eq!(count_parts(&captured[2], TYPE_PLUGIN), 1, "...and Plugin");
    assert_eq!(count_parts(&captured[2], TYPE_TYPE), 1, "...and Type");
    assert_eq!(
        count_parts(&captured[2], TYPE_TYPE_INSTANCE),
        0,
        "...but never a stale TypeInstance"
    );
    assert_eq!(
        count_parts(&captured[1], TYPE_TYPE_INSTANCE),
        0,
        "the notification never had one either"
    );

    assert_eq!(decoded, batch, "the whole three-event batch must survive the relay unchanged");
}

// -- decode only ------------------------------------------------------------------------------------

/// A listener whose diagnostics, decoder-side included, land in a [`Registry`] this test reads.
async fn diagnostic_harness() -> (Harness, Arc<Registry>) {
    let registry = Registry::new();
    let diag = Diagnostics::new("collectd_in").with_telemetry(registry.telemetry_for(
        "in/diag",
        "collectd_in",
        "input",
    ));
    (Harness::with_diagnostics(diag).await, registry)
}

/// A `0x0210` Encryption part stops the walk: the list before it is kept, and the ciphertext after
/// it never decodes.
#[tokio::test]
async fn an_encryption_part_drops_the_datagram_tail_and_is_counted() {
    let (mut harness, registry) = diagnostic_harness().await;
    harness.send_raw(&read_fixture("encrypted", "in")).await;
    let batch = harness.drain_decoded().await;

    assert_eq!(batch.events.len(), 1, "only the plaintext list before the Encryption part");
    assert_eq!(batch.events[0].metrics[0].kind, MetricKind::Gauge(3600.0));
    assert!(
        counted(&registry, "logit.component.diagnostics", ("key", "encrypted_packet_dropped")),
        "the dropped tail must be reported, not silent"
    );
}

/// Normalization 7: a list with no `Time`/`TimeHR` part gets the datagram's receipt time.
/// collectd's own receiver rejects such a list; `logit` stamps it, as every listener does.
#[tokio::test]
async fn a_list_with_no_time_part_is_stamped_with_receipt_time() {
    let harness = Harness::new().await;
    let before =
        std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
            as i64;
    harness.send_raw(&read_fixture("no-time", "in")).await;
    let mut harness = harness;
    let batch = harness.drain_decoded().await;
    let after =
        std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
            as i64;

    assert_eq!(batch.events.len(), 1);
    let timestamp = batch.events[0].timestamp;
    assert!(
        (before..=after).contains(&timestamp),
        "expected a receipt-time stamp in {before}..={after}, got {timestamp}"
    );
}

/// A malformed part keeps the lists already decoded and abandons the rest, reported as
/// `bad_part`, not the listener's whole-datagram `bad_datagram`.
#[tokio::test]
async fn a_truncated_values_part_keeps_the_lists_already_decoded_and_is_counted() {
    let (mut harness, registry) = diagnostic_harness().await;
    harness.send_raw(&read_fixture("truncated-values", "in")).await;
    let batch = harness.drain_decoded().await;

    assert_eq!(batch.events.len(), 1, "the well-formed list in front of the bad part survives");
    assert_eq!(batch.events[0].metrics[0].kind, MetricKind::Gauge(0.5));
    assert!(counted(&registry, "logit.component.diagnostics", ("key", "bad_part")));
}

/// An empty `Host` part clears the sticky host, so the list behind it is skipped, not treated as
/// a malformed datagram.
#[tokio::test]
async fn a_list_with_a_cleared_host_is_skipped_and_counted() {
    let (mut harness, registry) = diagnostic_harness().await;
    harness.send_raw(&read_fixture("incomplete-identity", "in")).await;
    let batch = harness.drain_decoded().await;

    assert_eq!(batch.events.len(), 1, "only the list that still had a host");
    assert_eq!(batch.events[0].metrics[0].kind, MetricKind::Gauge(0.5));
    assert!(counted(&registry, "logit.component.diagnostics", ("key", "incomplete_identity")));
}

// -- cross protocol: `statsd_in -> collectd_out` -----------------------------------------------------

/// A live `statsd_in` decoding raw statsd bytes, beside a collectd [`Harness`] for the
/// `collectd_out` leg.
struct CrossHarness {
    collectd: Harness,
    statsd_addr: SocketAddr,
    statsd_rx: mpsc::Receiver<Delivered>,
}

impl CrossHarness {
    async fn new() -> Self {
        let collectd = Harness::new().await;
        let mut input = StatsdInput::new("127.0.0.1:0");
        input.bind().await.expect("binding the statsd_in listener");
        let statsd_addr = input.local_addr().expect("bind() should leave a real address behind");
        let (tx, statsd_rx) = mpsc::channel(16);
        let sink = Fanout::new(vec![tx]);
        tokio::spawn(async move {
            let _ = input.run(sink).await;
        });
        Self { collectd, statsd_addr, statsd_rx }
    }

    /// The `EventBatch` a live `statsd_in` decodes from `line`.
    async fn statsd_decode(&mut self, line: &[u8]) -> EventBatch {
        let sender =
            UdpSocket::bind("127.0.0.1:0").await.expect("binding an ephemeral sender socket");
        sender.send_to(line, self.statsd_addr).await.expect("sending the statsd line");
        let delivered = tokio::time::timeout(FIRST, self.statsd_rx.recv())
            .await
            .expect("statsd_in should decode and forward the batch")
            .expect("the Fanout channel should not have closed");
        logit_pipeline::unwrap_batch(delivered)
    }
}

/// A statsd counter has no collectd identity, so it takes the encoder's fallback path: plugin is
/// the metric name up to its first `.`, type is the stock single-data-source `types.db` name for
/// its kind. `hits:5|c` is a delta, monotonic `Sum`, which is collectd's ABSOLUTE.
#[tokio::test]
async fn a_statsd_counter_relays_as_one_absolute_list() {
    let mut cross = CrossHarness::new().await;
    let batch = cross.statsd_decode(b"hits:5|c").await;
    assert_eq!(batch.events.len(), 1);

    let (captured, decoded) = cross
        .collectd
        .round_trip_with(&batch, |sink| {
            // `with_encoder` re-applies the sink's cap, diagnostics, and telemetry, so this
            // doesn't revert to `CollectdEncoder::new()`'s uncapped default.
            sink.with_encoder(CollectdEncoder::new().with_hostname("relay-host"))
        })
        .await;
    assert_eq!(captured.len(), 1);

    assert_eq!(decoded.events.len(), 1, "one record, one single-data-source value list");
    let event = &decoded.events[0];
    assert_eq!(attr(event, ATTR_HOST), Some(Value::from("relay-host")));
    assert_eq!(attr(event, ATTR_PLUGIN), Some(Value::from("hits")));
    assert_eq!(attr(event, ATTR_TYPE), Some(Value::from("absolute")));
    assert_eq!(attr(event, ATTR_PLUGIN_INSTANCE), None);
    assert_eq!(attr(event, ATTR_TYPE_INSTANCE), None, "`hits` has no dot to split an instance off");
    assert_eq!(name_of(&event.metrics[0]), "hits.absolute");
    match &event.metrics[0].kind {
        MetricKind::Sum(sum) => {
            assert_eq!(sum.value, 5.0);
            assert_eq!(sum.temporality, logit_core::Temporality::Delta);
            assert!(sum.monotonic);
        }
        other => panic!("expected a delta monotonic Sum, got {other:?}"),
    }
}

/// `@0.3` extrapolates `2` to `6.666…`, and collectd's COUNTER/DERIVE/ABSOLUTE are integral, so
/// the list is dropped and counted rather than rounded to a number nobody sent. No datagram is
/// sent, so this asserts the sink's counter.
#[tokio::test]
async fn a_sampled_statsd_counter_with_a_fractional_value_is_dropped_and_counted() {
    let mut cross = CrossHarness::new().await;
    let batch = cross.statsd_decode(b"page.views:2|c|@0.3").await;
    let value = match &batch.events[0].metrics[0].kind {
        MetricKind::Sum(sum) => sum.value,
        other => panic!("expected a Sum, got {other:?}"),
    };
    assert!((value - 6.666_666_666_666_667).abs() < 1e-9, "the fixture's premise: {value}");

    let registry = Registry::new();
    let mut sink = CollectdOutput::udp(cross.collectd.capture_addr.to_string())
        .unwrap()
        .with_telemetry(registry.telemetry_for("out", "collectd_out", "sink"))
        .with_encoder(CollectdEncoder::new().with_hostname("relay-host"));
    sink.send(&batch).await.expect("a fully-dropped batch is not a send error");

    assert!(
        counted(&registry, "logit.output.metrics.skipped", ("reason", "unencodable_value")),
        "the drop must be counted, not silent"
    );
}

/// collectd has no tags, so a DogStatsD tag is dropped and counted, once per attribute per event.
/// The gauge relays intact.
#[tokio::test]
async fn a_tagged_statsd_gauge_relays_as_a_gauge_with_its_tag_counted_away() {
    let mut cross = CrossHarness::new().await;
    let batch = cross.statsd_decode(b"temp:21.5|g|#env:prod").await;
    assert_eq!(batch.events[0].attributes.get("env").and_then(Value::as_str), Some("prod"));

    let registry = Registry::new();
    let telemetry = registry.telemetry_for("out", "collectd_out", "sink");
    let (captured, decoded) = cross
        .collectd
        .round_trip_with(&batch, |sink| {
            // Telemetry before encoder: `with_encoder` must keep the handle the codec's counters
            // use (`CollectdOutput::with_encoder`).
            sink.with_telemetry(telemetry.clone())
                .with_encoder(CollectdEncoder::new().with_hostname("relay-host"))
        })
        .await;
    assert_eq!(captured.len(), 1);

    let event = &decoded.events[0];
    assert_eq!(attr(event, ATTR_PLUGIN), Some(Value::from("temp")));
    assert_eq!(attr(event, ATTR_TYPE), Some(Value::from("gauge")));
    assert_eq!(name_of(&event.metrics[0]), "temp.gauge");
    assert_eq!(event.metrics[0].kind, MetricKind::Gauge(21.5));
    assert_eq!(event.attributes.get("env"), None, "collectd has no wire form for a tag");

    // Both sinks share one `Telemetry`, so the tag is counted once per sink.
    let events = registry.drain(0);
    assert_eq!(
        metric_sum(&events, "logit.output.tags.dropped", ("reason", "no_wire_form")),
        2.0,
        "`env` has no wire form, and is counted once on each of the two sinks this case sends \
         through"
    );
}

// -- `collectd_in -> aggregate -> collectd_out` --------------------------------------------------------

/// COUNTER and DERIVE decode to a cumulative `Sum`, which `aggregate` forwards untouched
/// (`passes_through`: re-accumulating a running total would double-count it), so the datagram is
/// byte-identical to the one with no `aggregate`. ABSOLUTE (a delta `Sum`) and GAUGE are absorbed
/// and re-stamped with the flush clock, which is why `fixtures/collectd-relay.yaml` has no
/// `aggregate`.
#[tokio::test]
async fn collectd_in_aggregate_collectd_out_relay_is_exact_for_cumulative_sums() {
    let raw = read_fixture("if-octets-derive", "in");
    let batch = direct_batch(&raw);
    let mut harness = Harness::new().await;

    // The baseline: the same fixture with no `aggregate` in the middle.
    let (direct, _) = harness.round_trip(&batch).await;

    let mut aggregator = Aggregator::new(Duration::from_secs(10));
    let resource = batch.resource.clone();
    let forwarded: Vec<logit_core::Event> = batch
        .events
        .iter()
        .cloned()
        .filter_map(|mut event| aggregator.process(&resource, &mut event).then_some(event))
        .collect();
    assert_eq!(
        forwarded.len(),
        batch.events.len(),
        "a cumulative Sum passes straight through aggregate, unabsorbed"
    );
    let windowed = EventBatch { resource, scope: None, events: forwarded };
    assert_eq!(
        windowed, batch,
        "and passes through *unchanged* -- timestamp and identity included"
    );

    let (through_aggregate, decoded) = harness.round_trip(&windowed).await;
    assert_eq!(
        through_aggregate, direct,
        "an aggregate window between the two ends must not change one byte of the relay"
    );
    assert_eq!(decoded, batch);

    // Nothing was absorbed, so there is nothing for the window to flush.
    assert!(
        aggregator.flush(1_800_000_000_000_000_000).is_empty(),
        "a window that absorbed nothing has nothing to emit"
    );
}
