//! `collectd_in -> collectd_out` round trip, over real UDP sockets -- the collectd counterpart to
//! `syslog_round_trip.rs`/`statsd_round_trip.rs`/`otlp_round_trip.rs`. Lives here (not a
//! dev-dependency cycle between `logit-inputs`/`logit-outputs`) for the same reason those do:
//! `logit-cli` already depends on both as ordinary dependencies.
//!
//! `docs/plans/collectd-binary-relay.md`'s W4 workstream, "Socket round trip" bullet.
//!
//! ## Fixture corpus (`tests/fixtures/collectd/`)
//!
//! One file pair per byte-for-byte case: `<name>.in` (a raw collectd datagram, exactly as a real
//! `network`-plugin sender would put it on the wire) and `<name>.expected` (the exact datagram
//! `collectd_out` must emit for that input's decode, or the literal marker [`SAME_AS_INPUT`] when
//! the sink reproduces the input verbatim) -- the same convention `syslog_round_trip.rs`'s and
//! `statsd_round_trip.rs`'s corpora use. The decode-only cases and `repacked-at-1024` carry an
//! `.in` alone: neither makes a byte-for-byte claim.
//!
//! Unlike those two corpora the files are **binary**, so the bytes are not self-describing. Every
//! `.in` is therefore also built in code, by [`build_in`]'s test-side [`PacketBuilder`] --
//! deliberately independent of `logit_proto::collectd::part`'s own writers, so a fixture proves the
//! codec agrees with the *protocol* rather than with itself -- and
//! [`every_committed_in_file_matches_its_builder`] pins the committed bytes against it. Read
//! [`build_in`] to see what a fixture is; read the file to hex-dump what it became.
//!
//! Each `.expected` was generated by running this same harness (a real `collectd_out` at a real
//! capture socket) and then reviewed as a hex dump, part by part, against the numbered list below
//! -- the `prometheus_round_trip.rs` discipline. This file's job is to prove the *real sockets and
//! components* compose to that result, not to re-litigate the codec's own correctness, which
//! `crates/logit-proto/tests/collectd_fixed_point.rs` already fixed-points and proptests.
//!
//! The three `testdata/interop/collectd/*.raw` captures from a real Debian `collectd` are **not**
//! copied into this corpus: they are replayed where they already live, by
//! `crates/logit-inputs/src/collectd.rs`'s own `interop_fixture_*` tests.
//!
//! ## Permitted normalizations
//!
//! Transcribed from [`logit_proto::collectd`]'s module doc, which is the codec's own spec. (ADR
//! [`collectd-binary-relay`](../../../docs/adr/collectd-binary-relay.md) carries the identical
//! list, with (3) below split into two entries -- string elision and datagram boundaries -- so its
//! numbering runs one higher from there on. The numbering used throughout this file is the codec
//! module doc's.)
//!
//! 1. Legacy `Time`/`Interval` (second resolution) re-emit as their `TimeHR`/`IntervalHR`
//!    (2⁻³⁰ s) counterparts.
//! 2. A `TimeHR` may move by at most one tick (2⁻³⁰ s ≈ 0.93 ns) on the first hop, and is stable
//!    afterward -- `cdtime → ns → cdtime` is not quite the identity, `ns → cdtime → ns` is.
//! 3. String-part elision is recomputed per *output* datagram, and datagram boundaries are
//!    re-chosen by the sink's own `max_packet_bytes`.
//! 4. Value lists may be reordered within a batch.
//! 5. Unknown part types and Signature parts are dropped.
//! 6. A NaN gauge's payload bits canonicalize.
//! 7. A list that arrived with no `Time` part at all leaves carrying `TimeHR = received_at`.
//! 8. `/` and NUL become `_`, and an identity field longer than 127 bytes is truncated.
//! 9. An absent interval leaves as `IntervalHR 0`.
//! 10. `TimeHR`/`IntervalHR` are written for **every** value list, so a sender's elided (unchanged)
//!     time or interval part is restored.
//!
//! **(10) is worth spelling out, because it is the one that costs bytes.** `collectd_out` re-states
//! both numeric parts on every list and never elides an unchanged one
//! (`logit_proto::collectd::encode`'s `write_list`), where a real collectd sender does elide
//! them -- the committed capture `testdata/interop/collectd/collectd-000.raw` carries 26 value
//! lists behind 17 `TimeHR` parts and a single `IntervalHR`. Restoring them is
//! information-preserving (a restored part carries exactly what the receiver's sticky state already
//! held), but a relayed datagram grows and may split: that 1296-byte capture re-encodes to 1717
//! bytes in two datagrams. [`elided_time_and_interval_parts_are_restored_per_list`] pins the
//! byte-level shape on the `elided-time-interval` fixture, and
//! [`a_real_collectd_capture_grows_when_its_elided_time_parts_are_restored`] pins those numbers
//! against the real capture.
//!
//! ## Per-fixture normalizations
//!
//! Byte-for-byte cases (each asserts both halves: the captured datagram equals `.expected`, and
//! `decode(sink output)` equals the original decode as a whole `EventBatch`):
//!
//! | Fixture | Normalizations | What it pins |
//! |---|---|---|
//! | `single-gauge` | none ([`SAME_AS_INPUT`]) | the baseline: one GAUGE list, `f64` little-endian, full identity, exact `TimeHR`/`IntervalHR` |
//! | `legacy-time-interval` | **1** | a second-resolution `Time`(0x0001)/`Interval`(0x0007) pair re-emitted as `TimeHR`(0x0008)/`IntervalHR`(0x0009) -- the only fixture whose `.expected` differs from its `.in` in a part *type* |
//! | `multi-value-load` | none ([`SAME_AS_INPUT`]) | a 3-data-source list is one event with three records in wire order, re-emitted as one list, not three |
//! | `if-octets-derive` | none ([`SAME_AS_INPUT`]) | a negative DERIVE (`i64`, big-endian) survives the `f64` model round trip |
//! | `counter-and-absolute` | none ([`SAME_AS_INPUT`]) | `u64::MAX` COUNTER -- the value that only round-trips because `as_u64`'s bound is inclusive and the cast saturates -- beside an ABSOLUTE |
//! | `elided-identity` | **3** | three lists differing only in `TypeInstance`; the sender's elision and this encoder's recomputed elision agree exactly, so it stays [`SAME_AS_INPUT`] |
//! | `elided-time-interval` | **10** | two lists stating `TimeHR`/`IntervalHR` once, the way a real sender writes them; the `.expected` re-states both on the second list, +24 B |
//! | `empty-instances` | **3** | explicit *empty* `PluginInstance`/`TypeInstance` parts (a sender clearing an instance) decode to absent attributes and leave elided entirely -- elision recomputed, in the removing direction |
//! | `no-interval` | **9** | two lists with no `Interval`/`IntervalHR` part at all; the `.expected` gains an explicit `IntervalHR 0` -- collectd's own "unspecified" -- on each, +24 B |
//! | `non-utf8-host` | none ([`SAME_AS_INPUT`]) | a `0xFF` in `Host` decodes to `Value::Bytes` and is re-emitted byte-verbatim, never lossily replaced |
//! | `unknown-and-signature-parts` | **5** | a `0x00FF` part from a future collectd and a `0x0200` Signature part, both between two lists: skipped by length, dropped on egress, and the list behind them still decodes |
//! | `nan-gauge` | **6** | a non-canonical NaN payload (`0xFFF8_0000_0000_0001`) decodes to a `NO_RECORDED_VALUE`-flagged `Gauge(0.0)` and leaves as this platform's canonical `f64::NAN` |
//! | `sub-second-time` | **2** | a `cdtime_t` with live sub-second bits, chosen because it genuinely *does* move: the first hop shifts it by one 2⁻³⁰ s tick, the second is byte-identical to the first (both asserted, neither assumed) |
//!
//! One case asserts its `.expected` wire bytes **only**, with no decoded-equality claim, because it
//! is genuinely one-way lossy -- the substituted byte is gone for good. (`statsd_round_trip.rs`'s
//! `sanitizer-*` cases are the same shape, for the same reason.)
//!
//! | Fixture | Normalizations | What it pins |
//! |---|---|---|
//! | `slash-in-plugin` | **8** | a `Plugin` of `mount/data` and a `TypeInstance` of `/var/log` leave as `mount_data` and `_var_log` (collectd's own `escape_slashes`, which its receiver would otherwise apply itself), counted `logit.output.identity.sanitized{reason="substituted"}` |
//!
//! One structural case, where the whole point is that bytes are *allowed* to move:
//!
//! | Fixture | Normalizations | What it pins |
//! |---|---|---|
//! | `repacked-at-1024` | **3**, **9** | 30 lists in one 1412-byte input carrying no interval part, re-packed by a sink capped at 1024: ≥2 datagrams, none over the cap, whole-batch equality. No `.expected` -- datagram boundaries are exactly what this case lets move, which is also why the `IntervalHR 0` it gains per list is pinned byte-for-byte by `no-interval` above rather than here |
//!
//! Decode-only cases, replayed through the live `collectd_in` and asserted on the delivered events
//! plus the throttled-diagnostic counters a [`Registry`] collects:
//!
//! | Fixture | Diagnostic | What it pins |
//! |---|---|---|
//! | `encrypted` | `encrypted_packet_dropped` | a `0x0210` Encryption part stops the walk: the list before it is kept, the list behind it never decodes |
//! | `no-time` | none | normalization **7** from the decode side: no `Time`/`TimeHR` part at all stamps `received_at` |
//! | `truncated-values` | `bad_part` | a `Values` header declaring more bytes than the datagram holds abandons the rest and keeps what was already decoded |
//! | `incomplete-identity` | `incomplete_identity` | an empty `Host` part clears the sticky host, and the list behind it is skipped exactly as collectd's own receiver rejects it |
//!
//! ## What this corpus does *not* cover
//!
//! ADR `lossless-transit` reads "no fixture" as "not covered", so the two remaining items are named
//! rather than left to inference:
//!
//! - **Normalization 4 (list reordering within a batch)** has no fixture here and needs none: it is
//!   a *permission* this pair never exercises. `CollectdEncoder::encode_into` walks
//!   `EventBatch::events` in order and emits one list per record in `MetricList` order, and
//!   `crates/logit-proto/tests/collectd_fixed_point.rs` pins that -- its `decode(encode(b)) == b`
//!   compares an ordered `Vec<Event>`, so any reordering the encoder introduced would fail it. The
//!   entry exists to license a *downstream* reorder (a `Fanout`, a buffered sink retry), not one
//!   this codec performs.
//! - **Notifications** (`Message` 0x0100 / `Severity` 0x0101) are the one wire feature this pair
//!   does not carry yet: they are skipped by length on decode and never emitted on encode. W5 of
//!   `docs/plans/collectd-binary-relay.md` adds them, and its own corpus fixtures with them; until
//!   it lands, `collectd_in -> collectd_out` is a fixed point for *value lists* only.
//!
//! ## Cross-protocol
//!
//! `statsd_in -> collectd_out` exercises the encoder's *fallback* path (no `collectd.*` identity at
//! all) over real sockets, including the two drops that path is most likely to hit in production:
//! a sampled statsd counter's non-integral extrapolation, and a DogStatsD tag that collectd has no
//! wire form for. `collectd_in -> aggregate -> collectd_out` pins that a cumulative `Sum` -- what a
//! COUNTER and a DERIVE both decode to -- passes straight through `aggregate` untouched, so the
//! relay stays byte-identical with a window in the middle.

use bytes::Bytes;
use logit_core::{Diagnostics, EventBatch, MetricKind, Registry, Resource, Value};
use logit_inputs::collectd::CollectdInput;
use logit_inputs::statsd::StatsdInput;
use logit_outputs::collectd::CollectdOutput;
use logit_pipeline::{Delivered, Fanout, Input, Output};
use logit_proto::collectd::{
    CollectdDecoder, CollectdEncoder, ATTR_HOST, ATTR_PLUGIN, ATTR_PLUGIN_INSTANCE, ATTR_TYPE,
    ATTR_TYPE_INSTANCE, DEFAULT_MAX_PACKET_BYTES,
};
use logit_proto::Decoder;
use logit_transforms::Aggregator;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;
use tokio::net::UdpSocket;
use tokio::sync::mpsc;

/// The `.expected` marker meaning "byte-identical to the `.in` file" -- see this file's module doc,
/// mirroring `syslog_round_trip.rs`/`statsd_round_trip.rs`'s identical constant.
const SAME_AS_INPUT: &[u8] = b"== SAME AS INPUT ==";

// -- the wire, written by hand -------------------------------------------------------------------
//
// Deliberately *not* `logit_proto::collectd::part`'s writers: a fixture built by the same code the
// encoder uses could not prove the encoder writes what a real collectd sender does, and could not
// express the legacy and malformed shapes this corpus needs. Same stance
// `crates/logit-proto/tests/collectd_fixed_point.rs` takes for its own grammar.

const TYPE_HOST: u16 = 0x0000;
const TYPE_TIME: u16 = 0x0001;
const TYPE_PLUGIN: u16 = 0x0002;
const TYPE_PLUGIN_INSTANCE: u16 = 0x0003;
const TYPE_TYPE: u16 = 0x0004;
const TYPE_TYPE_INSTANCE: u16 = 0x0005;
const TYPE_VALUES: u16 = 0x0006;
const TYPE_INTERVAL: u16 = 0x0007;
const TYPE_TIME_HR: u16 = 0x0008;
const TYPE_INTERVAL_HR: u16 = 0x0009;
const TYPE_SIGNATURE: u16 = 0x0200;
const TYPE_ENCRYPTION: u16 = 0x0210;
/// A part type no collectd defines -- normalization 5's "unknown part types are skipped by length."
const TYPE_FROM_THE_FUTURE: u16 = 0x00FF;

/// Bytes of a numeric part: the four-byte header plus one `u64` BE.
const NUMBER_PART_LEN: usize = 12;

const DS_COUNTER: u8 = 0;
const DS_GAUGE: u8 = 1;
const DS_DERIVE: u8 = 2;
const DS_ABSOLUTE: u8 = 3;

/// `2023-11-14T22:13:20Z` in whole seconds, the instant every fixture in this corpus is stamped
/// with -- far enough from "now" that a receipt-time fallback (normalization 7) is unmistakable.
const TIME_SECONDS: u64 = 1_700_000_000;
/// [`TIME_SECONDS`] as a `cdtime_t`.
const TIME_HR: u64 = TIME_SECONDS << 30;
/// A ten-second `Interval`, as a `cdtime_t`.
const INTERVAL_HR: u64 = 10 << 30;
/// The sub-second half of `sub-second-time`'s `TimeHR`. Not an arbitrary bit pattern: most tick
/// values survive `cdtime → ns → cdtime` untouched, and a fixture that happened to pick one would
/// claim to exercise normalization 2 while exercising nothing at all. This one moves by exactly
/// one tick on the first hop (and is then stable), which is what
/// [`a_sub_second_time_moves_at_most_one_tick_and_is_then_stable`] asserts.
const SUB_SECOND_TICKS: u64 = 0x1234_567E;

#[derive(Default)]
struct PacketBuilder {
    bytes: Vec<u8>,
}

impl PacketBuilder {
    fn new() -> Self {
        Self::default()
    }

    /// `type: u16 BE, len: u16 BE` (the length *including* these four bytes), then the payload.
    fn part(mut self, part_type: u16, payload: &[u8]) -> Self {
        let len = (4 + payload.len()) as u16;
        self.bytes.extend_from_slice(&part_type.to_be_bytes());
        self.bytes.extend_from_slice(&len.to_be_bytes());
        self.bytes.extend_from_slice(payload);
        self
    }

    /// A NUL-terminated string part. An empty `value` is the five-byte part a sender writes to
    /// *clear* a sticky field, which is not the same as omitting the part.
    fn string(self, part_type: u16, value: &[u8]) -> Self {
        let mut payload = value.to_vec();
        payload.push(0);
        self.part(part_type, &payload)
    }

    /// A `u64`-BE numeric part.
    fn number(self, part_type: u16, value: u64) -> Self {
        self.part(part_type, &value.to_be_bytes())
    }

    /// A Values part: the `u16` data-source count, then every type byte, then every eight-byte
    /// value -- two vectors, not interleaved pairs.
    fn values(self, values: &[(u8, [u8; 8])]) -> Self {
        let mut payload = Vec::new();
        payload.extend_from_slice(&(values.len() as u16).to_be_bytes());
        for (ds_type, _) in values {
            payload.push(*ds_type);
        }
        for (_, raw) in values {
            payload.extend_from_slice(raw);
        }
        self.part(TYPE_VALUES, &payload)
    }

    /// Raw bytes with no framing at all -- for the deliberately malformed tail
    /// `truncated-values` ends in.
    fn raw(mut self, bytes: &[u8]) -> Self {
        self.bytes.extend_from_slice(bytes);
        self
    }

    fn build(self) -> Vec<u8> {
        self.bytes
    }
}

fn gauge(value: f64) -> (u8, [u8; 8]) {
    // Little-endian, unlike every other value type on this wire -- collectd writes `htole64` for
    // gauges specifically.
    (DS_GAUGE, value.to_le_bytes())
}

/// A GAUGE carrying an exact NaN *bit pattern*, which `f64::to_le_bytes` could not be trusted to
/// preserve through a `f64` literal.
fn gauge_bits(bits: u64) -> (u8, [u8; 8]) {
    (DS_GAUGE, bits.to_le_bytes())
}

fn counter(value: u64) -> (u8, [u8; 8]) {
    (DS_COUNTER, value.to_be_bytes())
}

fn derive(value: i64) -> (u8, [u8; 8]) {
    (DS_DERIVE, value.to_be_bytes())
}

fn absolute(value: u64) -> (u8, [u8; 8]) {
    (DS_ABSOLUTE, value.to_be_bytes())
}

/// Every `.in` file in the corpus, as the bytes a real sender would write. The committed files are
/// pinned against this by [`every_committed_in_file_matches_its_builder`]; this function is the
/// readable half of the corpus, and the files are the reviewable one.
///
/// Part order throughout is collectd's own `add_to_buffer` order -- Host, Time, Interval, Plugin,
/// PluginInstance, Type, TypeInstance, Values -- which is also the order `collectd_out` writes, so
/// a fixture that changes nothing else stays [`SAME_AS_INPUT`].
fn build_in(name: &str) -> Vec<u8> {
    match name {
        // -- byte for byte ---------------------------------------------------------------------
        "single-gauge" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"used")
            .values(&[gauge(1.5)])
            .build(),

        // The legacy second-resolution pair, which no modern collectd writes but every one still
        // accepts -- and which this codec re-emits only as TimeHR/IntervalHR (normalization 1).
        "legacy-time-interval" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME, TIME_SECONDS)
            .number(TYPE_INTERVAL, 10)
            .string(TYPE_PLUGIN, b"cpu")
            .string(TYPE_PLUGIN_INSTANCE, b"0")
            .string(TYPE_TYPE, b"cpu")
            .string(TYPE_TYPE_INSTANCE, b"user")
            .values(&[derive(12_345)])
            .build(),

        // `load`'s three data sources: one Values part, therefore one event carrying three records
        // in wire order, therefore one Values part again on the way out.
        "multi-value-load" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .values(&[gauge(0.05), gauge(0.15), gauge(0.25)])
            .build(),

        // Both values stay inside 2^53, where an `i64` is exactly representable as an `f64` -- above
        // it the model's own int/double collapse (`docs/known-gaps.md`) would move the value, which
        // is a documented gap rather than anything this corpus should assert byte-equality across.
        "if-octets-derive" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"interface")
            .string(TYPE_PLUGIN_INSTANCE, b"eth0")
            .string(TYPE_TYPE, b"if_octets")
            .values(&[derive(1_234_567_890_123), derive(-42)])
            .build(),

        // `u64::MAX` is the one COUNTER that only survives because `as_u64`'s upper bound is
        // inclusive and the `as` cast saturates: it decodes to the `f64` 2^64 (the nearest
        // representable double), which an exclusive bound would drop.
        "counter-and-absolute" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"disk")
            .string(TYPE_PLUGIN_INSTANCE, b"sda")
            .string(TYPE_TYPE, b"disk_ops")
            .values(&[counter(u64::MAX), absolute(17)])
            .build(),

        // Three lists sharing one identity, only `TypeInstance` moving -- the protocol's whole
        // compression scheme. See the module doc for why TimeHR/IntervalHR are re-stated per list.
        "elided-identity" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"cpu")
            .string(TYPE_PLUGIN_INSTANCE, b"0")
            .string(TYPE_TYPE, b"cpu")
            .string(TYPE_TYPE_INSTANCE, b"user")
            .values(&[derive(100)])
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_TYPE_INSTANCE, b"system")
            .values(&[derive(50)])
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_TYPE_INSTANCE, b"idle")
            .values(&[derive(900)])
            .build(),

        // The elision a real collectd actually performs, and the one `collectd_out` does not
        // reproduce: `TimeHR`/`IntervalHR` stated once, inherited by the second list. Normalization
        // 10 -- the `.expected` re-states both, 24 bytes larger than what arrived.
        "elided-time-interval" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"cpu")
            .string(TYPE_PLUGIN_INSTANCE, b"0")
            .string(TYPE_TYPE, b"cpu")
            .string(TYPE_TYPE_INSTANCE, b"user")
            .values(&[derive(100)])
            .string(TYPE_TYPE_INSTANCE, b"system")
            .values(&[derive(50)])
            .build(),

        // Two five-byte string parts carrying nothing but their NUL: how a sender *clears* a
        // sticky instance it set earlier in the same datagram.
        "empty-instances" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"df")
            .string(TYPE_PLUGIN_INSTANCE, b"")
            .string(TYPE_TYPE, b"df_complex")
            .string(TYPE_TYPE_INSTANCE, b"")
            .values(&[gauge(1024.0)])
            .build(),

        // No Interval part of either resolution -- collectd's `network` plugin omits one when the
        // value list's own interval matches the daemon's global default. Normalization 9: the
        // `.expected` gains an explicit `IntervalHR 0`, collectd's own "unspecified", on each list.
        // `TimeHR` is deliberately re-stated on the second list so the *only* difference between
        // `.in` and `.expected` is normalization 9, not 10 as well.
        "no-interval" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"used")
            .values(&[gauge(1.5)])
            .number(TYPE_TIME_HR, TIME_HR)
            .string(TYPE_TYPE_INSTANCE, b"free")
            .values(&[gauge(2.5)])
            .build(),

        // Normalization 8's substitution half, reachable from a real decode: collectd's own
        // receiver runs `escape_slashes` over an identity it accepts, so a sender that writes a
        // raw path -- a `df` plugin instance, a mount point -- is writing something every receiver
        // rewrites. This codec does the rewriting on egress instead, and counts it. Genuinely
        // one-way: the `/` is gone, so this fixture asserts wire bytes only.
        "slash-in-plugin" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"mount/data")
            .string(TYPE_TYPE, b"df_complex")
            .string(TYPE_TYPE_INSTANCE, b"/var/log")
            .values(&[gauge(7.0)])
            .build(),

        // collectd's strings are bytes, not text: a host name from a non-UTF-8 locale is a real
        // thing to receive.
        "non-utf8-host" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-\xff-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"free")
            .values(&[gauge(2.5)])
            .build(),

        // A part type from a collectd newer than this codec, and a `SecurityLevel Sign` sender's
        // Signature part (an HMAC-SHA256 over the plaintext that follows, then the username) --
        // both skipped by length, both dropped on egress, and the list behind them still decodes.
        "unknown-and-signature-parts" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"swap")
            .string(TYPE_TYPE, b"swap")
            .string(TYPE_TYPE_INSTANCE, b"used")
            .values(&[gauge(100.0)])
            .part(TYPE_FROM_THE_FUTURE, b"a part type this codec has never heard of")
            .part(TYPE_SIGNATURE, &{
                let mut payload = vec![0xABu8; 32];
                payload.extend_from_slice(b"fixture-user");
                payload
            })
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_TYPE_INSTANCE, b"free")
            .values(&[gauge(200.0)])
            .build(),

        // A negative quiet NaN with a live payload bit: collectd's "no value this interval," spelt
        // in a bit pattern that is not the one this platform's `f64::NAN` has.
        "nan-gauge" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"sensors")
            .string(TYPE_PLUGIN_INSTANCE, b"coretemp")
            .string(TYPE_TYPE, b"temperature")
            .string(TYPE_TYPE_INSTANCE, b"core0")
            .values(&[gauge_bits(0xFFF8_0000_0000_0001)])
            .build(),

        // Every low bit of the cdtime live, which is what reaches normalization 2 -- a whole-second
        // TimeHR is bit-identical to its own legacy spelling and can never move.
        "sub-second-time" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR | SUB_SECOND_TICKS)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"processes")
            .string(TYPE_TYPE, b"ps_state")
            .string(TYPE_TYPE_INSTANCE, b"running")
            .values(&[gauge(42.0)])
            .build(),

        // 30 lists in one datagram that fits collectd's own 1452-byte default, carrying no interval
        // at all (normalization 9 on the way out) purely so all 30 fit. The sink re-packs them at
        // 1024.
        "repacked-at-1024" => {
            let mut builder = PacketBuilder::new()
                .string(TYPE_HOST, b"web-1")
                .number(TYPE_TIME_HR, TIME_HR)
                .string(TYPE_PLUGIN, b"cpu")
                .string(TYPE_PLUGIN_INSTANCE, b"0")
                .string(TYPE_TYPE, b"cpu");
            for index in 0..30u64 {
                if index > 0 {
                    builder = builder.number(TYPE_TIME_HR, TIME_HR);
                }
                builder = builder
                    .string(TYPE_TYPE_INSTANCE, format!("state-{index:02}-of-30").as_bytes())
                    .values(&[derive(index as i64 * 1000)]);
            }
            builder.build()
        }

        // -- decode only -------------------------------------------------------------------------

        // The second list is ciphertext as far as this codec is concerned, and must never decode.
        "encrypted" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"uptime")
            .string(TYPE_TYPE, b"uptime")
            .values(&[gauge(3600.0)])
            .part(TYPE_ENCRYPTION, &[0x5A; 48])
            .values(&[gauge(7200.0)])
            .build(),

        // No Time part of either resolution: normalization 7's receipt-time stamp.
        "no-time" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .string(TYPE_PLUGIN, b"memory")
            .string(TYPE_TYPE, b"memory")
            .string(TYPE_TYPE_INSTANCE, b"cached")
            .values(&[gauge(512.0)])
            .build(),

        // A Values header declaring 24 bytes with only six left in the datagram -- a packet cut
        // mid-part by a sender, a middlebox, or a hostile length.
        "truncated-values" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .values(&[gauge(0.5)])
            .raw(&[0x00, 0x06, 0x00, 0x18, 0x00, 0x02])
            .build(),

        // An empty Host part clears the sticky host, so the list behind it has no identity to
        // dispatch against -- exactly what collectd's own receiver rejects with `-EINVAL`.
        "incomplete-identity" => PacketBuilder::new()
            .string(TYPE_HOST, b"web-1")
            .number(TYPE_TIME_HR, TIME_HR)
            .number(TYPE_INTERVAL_HR, INTERVAL_HR)
            .string(TYPE_PLUGIN, b"load")
            .string(TYPE_TYPE, b"load")
            .values(&[gauge(0.5)])
            .string(TYPE_HOST, b"")
            .values(&[gauge(0.9)])
            .build(),

        other => panic!("no builder for fixture {other:?}"),
    }
}

/// The byte-for-byte cases: a `.in` and a `.expected` each, both halves asserted (captured
/// datagram == `.expected`, and `decode(sink output)` == the original decode as a whole
/// `EventBatch`). In the order the module doc's first table lists them.
const BYTE_FOR_BYTE: &[&str] = &[
    "single-gauge",
    "legacy-time-interval",
    "multi-value-load",
    "if-octets-derive",
    "counter-and-absolute",
    "elided-identity",
    "elided-time-interval",
    "empty-instances",
    "no-interval",
    "non-utf8-host",
    "unknown-and-signature-parts",
    "nan-gauge",
    "sub-second-time",
];

/// The one-way-lossy case: its `.expected` wire bytes are asserted, the decoded batch deliberately
/// is not (the substituted byte is gone for good). See the module doc's second table.
const ONE_WAY: &[&str] = &["slash-in-plugin"];

/// The structural case: an `.in` and no `.expected`, since the datagram boundaries are exactly what
/// it lets move.
const STRUCTURAL: &[&str] = &["repacked-at-1024"];

/// The decode-only cases: an `.in` each, replayed through the live listener and asserted on
/// delivered events and diagnostics rather than on any sink output.
const DECODE_ONLY: &[&str] = &["encrypted", "no-time", "truncated-values", "incomplete-identity"];

/// Every `.in` file this corpus commits.
fn in_fixtures() -> impl Iterator<Item = &'static str> {
    BYTE_FOR_BYTE.iter().chain(ONE_WAY).chain(STRUCTURAL).chain(DECODE_ONLY).copied()
}

// -- corpus files ---------------------------------------------------------------------------------

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/collectd")
}

/// The recorded-capture directory, read in place rather than copied into this corpus -- see
/// [`a_real_collectd_capture_grows_when_its_elided_time_parts_are_restored`], and
/// `syslog_round_trip.rs`'s identical helper.
fn testdata_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../testdata/interop/collectd")
}

/// How many parts of type `part_type` a datagram carries, walking it by the `len` in each header
/// the way any receiver does. Deliberately re-derived here rather than counting byte patterns: a
/// `0x0008` can appear inside a Values payload, and only the framing walk knows the difference.
fn count_parts(datagram: &[u8], part_type: u16) -> usize {
    let mut at = 0usize;
    let mut count = 0usize;
    while at + 4 <= datagram.len() {
        let this = u16::from_be_bytes([datagram[at], datagram[at + 1]]);
        let len = u16::from_be_bytes([datagram[at + 2], datagram[at + 3]]) as usize;
        assert!(len >= 4 && at + len <= datagram.len(), "malformed part at {at}");
        if this == part_type {
            count += 1;
        }
        at += len;
    }
    assert_eq!(at, datagram.len(), "the datagram should end on a part boundary");
    count
}

fn read(path: &Path) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

fn read_fixture(name: &str, ext: &str) -> Vec<u8> {
    read(&fixtures_dir().join(format!("{name}.{ext}")))
}

/// The bytes a case's sink output must equal: either the literal `.expected` file, or (when that
/// file is exactly [`SAME_AS_INPUT`]) the case's own `.in` bytes.
fn expected_bytes(name: &str, input: &[u8]) -> Vec<u8> {
    let expected = read_fixture(name, "expected");
    if expected.as_slice() == SAME_AS_INPUT {
        input.to_vec()
    } else {
        expected
    }
}

/// The committed binary corpus is only reviewable if something says what its bytes mean -- see the
/// module doc. This is that pin: every `.in` file is exactly what [`build_in`] says it is.
#[test]
fn every_committed_in_file_matches_its_builder() {
    for name in in_fixtures() {
        assert_eq!(
            read_fixture(name, "in"),
            build_in(name),
            "{name}.in has drifted from build_in()'s description of it"
        );
    }
}

// -- the harness ----------------------------------------------------------------------------------

fn direct_batch(raw: &[u8]) -> EventBatch {
    let mut decoder = CollectdDecoder::new(Arc::new(Resource::default()));
    decoder.decode(Bytes::copy_from_slice(raw)).expect("fixture should decode")
}

/// Real UDP harness: a plain "byte capture" socket (for the raw-datagram half of every byte-for-byte
/// assertion) alongside a real, bound [`CollectdInput`] draining into a [`Fanout`] channel (for the
/// decoded-`EventBatch` half). Mirrors `syslog_round_trip.rs`/`statsd_round_trip.rs`'s `Harness`
/// exactly: `bind()`-then-`local_addr()`-then-spawn, no bind-drop race and no sleep-based readiness
/// guess.
///
/// There is deliberately **no `normalize_receipt_time`** here, unlike both of those. Every
/// byte-for-byte fixture in this corpus carries a wire `Time`/`TimeHR` part, so `Event::timestamp`
/// is origin data on both sides of the relay and compares exactly; the one fixture that doesn't
/// (`no-time`) is decode-only and asserts the receipt-time stamp directly.
struct Harness {
    capture: UdpSocket,
    capture_addr: SocketAddr,
    input_addr: SocketAddr,
    rx: mpsc::Receiver<Delivered>,
}

/// How long to wait for the *first* datagram/batch of a send, and how long to keep waiting for more
/// after one has arrived. The second is what bounds "and nothing else came" assertions.
const FIRST: Duration = Duration::from_millis(500);
const SUBSEQUENT: Duration = Duration::from_millis(200);

impl Harness {
    async fn new() -> Self {
        let capture = UdpSocket::bind("127.0.0.1:0").await.expect("binding the capture socket");
        let capture_addr = capture.local_addr().expect("capture socket should have a local addr");

        let mut input = CollectdInput::new("127.0.0.1:0");
        input.bind().await.expect("binding the collectd_in listener");
        let input_addr = input.local_addr().expect("bind() should leave a real address behind");

        let (tx, rx) = mpsc::channel(64);
        let sink = Fanout::new(vec![tx]);
        tokio::spawn(async move {
            let _ = input.run(sink).await;
        });

        Self { capture, capture_addr, input_addr, rx }
    }

    /// A [`CollectdInput`] with its own diagnostics, for the decode-only cases -- built separately
    /// from [`Harness::new`]'s listener so the byte-for-byte corpus isn't paying for a `Registry`
    /// it never reads.
    async fn with_diagnostics(diag: Diagnostics) -> Self {
        let capture = UdpSocket::bind("127.0.0.1:0").await.expect("binding the capture socket");
        let capture_addr = capture.local_addr().expect("capture socket should have a local addr");

        let mut input = CollectdInput::new("127.0.0.1:0").with_diagnostics(diag);
        input.bind().await.expect("binding the collectd_in listener");
        let input_addr = input.local_addr().expect("bind() should leave a real address behind");

        let (tx, rx) = mpsc::channel(64);
        let sink = Fanout::new(vec![tx]);
        tokio::spawn(async move {
            let _ = input.run(sink).await;
        });

        Self { capture, capture_addr, input_addr, rx }
    }

    /// Sends `batch` through two fresh [`CollectdOutput`]s built the same way -- one aimed at the
    /// raw capture socket, one at the live `collectd_in` -- and returns every datagram the capture
    /// socket received alongside the [`EventBatch`] the real input decoded from the other copy.
    ///
    /// `configure` is applied to both sinks, so a cap (or a hostname) set for one leg is set for
    /// the other; it takes a fresh `CollectdOutput` each time rather than a shared one, since a
    /// sink owns a socket and cannot be aimed at two endpoints.
    async fn round_trip_with(
        &mut self,
        batch: &EventBatch,
        configure: impl Fn(CollectdOutput) -> CollectdOutput,
    ) -> (Vec<Vec<u8>>, EventBatch) {
        let captured = self.capture_only(batch, &configure).await;

        let mut to_input = configure(CollectdOutput::udp(self.input_addr.to_string()).unwrap());
        to_input.send(batch).await.expect("send to the live collectd_in");
        (captured, self.drain_decoded().await)
    }

    /// [`Harness::round_trip_with`] with the sink left exactly as `collectd_out`'s own defaults
    /// build it (`max_packet_bytes: 1452`, no `hostname:`).
    async fn round_trip(&mut self, batch: &EventBatch) -> (Vec<Vec<u8>>, EventBatch) {
        self.round_trip_with(batch, |sink| sink).await
    }

    /// Sends `batch` at the capture socket only, returning every datagram it received. Split out
    /// of [`Harness::round_trip_with`], its one caller, so the two legs of a round trip read as the
    /// two separate sends they are.
    async fn capture_only(
        &mut self,
        batch: &EventBatch,
        configure: impl Fn(CollectdOutput) -> CollectdOutput,
    ) -> Vec<Vec<u8>> {
        let mut to_capture = configure(CollectdOutput::udp(self.capture_addr.to_string()).unwrap());
        to_capture.send(batch).await.expect("send to the capture socket");
        self.drain_captured().await
    }

    /// Every datagram the capture socket holds: the first waited on for [`FIRST`], each one after
    /// it for [`SUBSEQUENT`] (so a single-datagram case costs one short wait, not a full one).
    async fn drain_captured(&mut self) -> Vec<Vec<u8>> {
        let mut buf = vec![0u8; 65_536];
        let mut datagrams = Vec::new();
        let mut wait = FIRST;
        while let Ok(result) = tokio::time::timeout(wait, self.capture.recv_from(&mut buf)).await {
            let (n, _) = result.expect("recv_from should succeed");
            datagrams.push(buf[..n].to_vec());
            wait = SUBSEQUENT;
        }
        assert!(!datagrams.is_empty(), "the capture socket received no datagram at all");
        datagrams
    }

    /// Every batch the live `collectd_in` delivered, flattened into one -- a multi-datagram send
    /// may arrive as one accumulated batch or as several, which is a batching decision this test
    /// has no business asserting on.
    async fn drain_decoded(&mut self) -> EventBatch {
        let mut batches = Vec::new();
        let mut wait = FIRST;
        while let Ok(delivered) = tokio::time::timeout(wait, self.rx.recv()).await {
            let delivered = delivered.expect("the Fanout channel should not have closed");
            batches.push(logit_pipeline::unwrap_batch(delivered));
            wait = SUBSEQUENT;
        }
        assert!(!batches.is_empty(), "collectd_in delivered nothing at all");
        let mut merged = batches.remove(0);
        for batch in batches {
            assert_eq!(batch.resource, merged.resource, "one decoder, one shared resource");
            assert!(batch.scope.is_none(), "collectd carries no scope concept");
            merged.events.extend(batch.events);
        }
        merged
    }

    /// Sends `raw` straight at the live `collectd_in`, bypassing `collectd_out` entirely -- for the
    /// decode-only cases, which are about what the *listener* does with bytes no encoder would ever
    /// produce.
    async fn send_raw(&self, raw: &[u8]) {
        let sender =
            UdpSocket::bind("127.0.0.1:0").await.expect("binding an ephemeral sender socket");
        sender.send_to(raw, self.input_addr).await.expect("sending the raw datagram");
    }
}

/// Whether `registry` recorded a point named `metric` carrying `tag`. Drains, so call once.
fn counted(registry: &Registry, metric: &str, tag: (&str, &str)) -> bool {
    registry.drain(0).into_iter().any(|event| {
        event.metrics.iter().any(|m| logit_core::interner::resolve(m.name) == metric)
            && event.attributes.get(tag.0).and_then(Value::as_str) == Some(tag.1)
    })
}

/// The summed value of every point named `metric` carrying `tag` in an already-drained `events`.
/// Takes the drained slice rather than the `Registry`: `drain` empties it, so reading several
/// metrics needs one shared drain, not one per metric.
fn metric_sum(events: &[logit_core::Event], metric: &str, tag: (&str, &str)) -> f64 {
    events
        .iter()
        .filter(|e| e.attributes.get(tag.0).and_then(Value::as_str) == Some(tag.1))
        .flat_map(|e| &e.metrics)
        .filter(|m| logit_core::interner::resolve(m.name) == metric)
        .map(|m| match &m.kind {
            MetricKind::Sum(sum) => sum.value,
            other => panic!("{metric} must be a counter, got {other:?}"),
        })
        .sum()
}

fn attr(event: &logit_core::Event, key: &str) -> Option<Value> {
    event.attributes.get(key).cloned()
}

fn name_of(record: &logit_core::MetricRecord) -> &'static str {
    logit_core::interner::resolve(record.name)
}

// -- byte for byte ---------------------------------------------------------------------------------

/// One deterministic byte-for-byte case: the fixture's own decode round-trips through a live
/// `collectd_in` unchanged (whole-`EventBatch` equality), and the single datagram the far end
/// actually received equals the case's `.expected` bytes (the module doc's normalization list
/// covers every place the two legitimately differ).
async fn assert_byte_for_byte(harness: &mut Harness, fixture: &str) {
    let raw = read_fixture(fixture, "in");
    let batch = direct_batch(&raw);
    let expected = expected_bytes(fixture, &raw);
    let (captured, decoded) = harness.round_trip(&batch).await;
    assert_eq!(
        captured.len(),
        1,
        "{fixture}: every byte-for-byte fixture fits one default-capped datagram"
    );
    assert_eq!(
        captured[0], expected,
        "{fixture}: raw datagram bytes should match .expected (modulo the module doc's permitted \
         normalizations)"
    );
    assert_eq!(
        decoded, batch,
        "{fixture}: decode(sink output) should equal the original decode, as a whole EventBatch"
    );
}

#[tokio::test]
async fn the_corpus_round_trips_byte_for_byte() {
    let mut harness = Harness::new().await;
    for fixture in BYTE_FOR_BYTE {
        assert_byte_for_byte(&mut harness, fixture).await;
    }
}

/// Normalization 8's substitution half ([`ONE_WAY`]): a `/` in an identity field is replaced with
/// `_` and counted, which is the one kind of change in this corpus that genuinely loses something
/// -- so the wire bytes are asserted against `.expected` and no decoded-equality claim is made, the
/// same shape `statsd_round_trip.rs`'s `sanitizer-*` cases have. The substituted identity is what
/// comes back on the far end, and the record name follows it.
#[tokio::test]
async fn a_slash_in_an_identity_field_is_substituted_counted_and_not_a_round_trip() {
    let raw = read_fixture("slash-in-plugin", "in");
    let batch = direct_batch(&raw);
    assert_eq!(
        attr(&batch.events[0], ATTR_PLUGIN),
        Some(Value::from("mount/data")),
        "the fixture's premise: the raw `/` survives decode untouched"
    );

    let registry = Registry::new();
    let telemetry = registry.telemetry_for("out", "collectd_out", "sink");
    let mut harness = Harness::new().await;
    let (captured, decoded) =
        harness.round_trip_with(&batch, |sink| sink.with_telemetry(telemetry.clone())).await;

    assert_eq!(captured.len(), 1);
    assert_eq!(captured[0], read_fixture("slash-in-plugin", "expected"));
    assert_ne!(captured[0], raw, "this fixture is one-way: the `/` does not survive");
    assert_eq!(attr(&decoded.events[0], ATTR_PLUGIN), Some(Value::from("mount_data")));
    assert_eq!(attr(&decoded.events[0], ATTR_TYPE_INSTANCE), Some(Value::from("_var_log")));
    assert_eq!(name_of(&decoded.events[0].metrics[0]), "mount_data.df_complex");

    // Three substituted fields -- `mount/data` once, `/var/log` twice -- but the counter is per
    // *field*, not per byte, and both sinks this case sends through count their own copy.
    let events = registry.drain(0);
    assert_eq!(
        metric_sum(&events, "logit.output.identity.sanitized", ("reason", "substituted")),
        4.0,
        "plugin and type_instance are each counted once per sink, over two sinks"
    );
}

/// Normalization 10, spelt out on the fixture built for it: a sender that states `TimeHR`/
/// `IntervalHR` once and lets the second list inherit them gets both parts back on every list.
/// Information-preserving -- the restored parts carry exactly what the receiver's sticky state
/// already held, which is why the decoded batches still compare equal -- but 24 bytes larger.
#[tokio::test]
async fn elided_time_and_interval_parts_are_restored_per_list() {
    let raw = read_fixture("elided-time-interval", "in");
    let expected = read_fixture("elided-time-interval", "expected");
    assert_eq!(
        expected.len(),
        raw.len() + 2 * NUMBER_PART_LEN,
        "one restored TimeHR and one restored IntervalHR, both 12-byte numeric parts"
    );
    assert_eq!(count_parts(&raw, TYPE_TIME_HR), 1);
    assert_eq!(count_parts(&raw, TYPE_INTERVAL_HR), 1);
    assert_eq!(count_parts(&expected, TYPE_TIME_HR), 2, "one per value list on egress");
    assert_eq!(count_parts(&expected, TYPE_INTERVAL_HR), 2);

    // Still asserted end to end by `the_corpus_round_trips_byte_for_byte`; repeated here so this
    // test stands alone as the account of normalization 10.
    let mut harness = Harness::new().await;
    assert_byte_for_byte(&mut harness, "elided-time-interval").await;
}

/// Normalization 10 against traffic nobody wrote for a test: the recorded capture in
/// `testdata/interop/collectd/` is a real Debian `collectd`'s own output, and it elides both
/// numeric parts aggressively -- 26 value lists behind 17 `TimeHR` parts and **one** `IntervalHR`.
/// Relaying it restores the missing 35, which is what turns one 1296-byte datagram into 1717 bytes
/// across two. These are the numbers `docs/adr/collectd-binary-relay.md`'s amendment and
/// `docs/deploying.md` quote at an operator, so they are pinned rather than described.
///
/// The capture is read where it lives, never copied into this corpus -- that directory's own README
/// asks for exactly that, and `crates/logit-inputs/src/collectd.rs`'s `interop_fixture_*` tests
/// already cover what it decodes to.
#[tokio::test]
async fn a_real_collectd_capture_grows_when_its_elided_time_parts_are_restored() {
    let raw = read(&testdata_dir().join("collectd-000.raw"));
    assert_eq!(raw.len(), 1296);
    assert_eq!(count_parts(&raw, TYPE_VALUES), 26, "26 value lists");
    assert_eq!(count_parts(&raw, TYPE_TIME_HR), 17, "...behind 17 TimeHR parts");
    assert_eq!(count_parts(&raw, TYPE_INTERVAL_HR), 1, "...and a single IntervalHR");

    let batch = direct_batch(&raw);
    assert_eq!(batch.events.len(), 26);

    let mut harness = Harness::new().await;
    let (captured, decoded) = harness.round_trip(&batch).await;
    let total: usize = captured.iter().map(Vec::len).sum();
    assert_eq!(captured.len(), 2, "the restored parts push it past the 1452-byte default cap");
    assert_eq!(total, 1717, "1296 bytes in, 1717 out -- about 30% more, per normalization 10");
    for datagram in &captured {
        assert!(datagram.len() <= DEFAULT_MAX_PACKET_BYTES, "each datagram still fits the cap");
        assert_eq!(
            count_parts(datagram, TYPE_TIME_HR),
            count_parts(datagram, TYPE_VALUES),
            "one TimeHR per value list, which is the whole point"
        );
    }

    // Bytes grew; information did not change. That is what makes this a normalization.
    assert_eq!(decoded, batch, "every one of the 26 lists survives the relay unchanged");
}

/// Spelt out beside the corpus loop because the claim is finer than "the bytes match": a
/// three-data-source `load` list is **one** event carrying three records in wire order, not three
/// events -- which is the whole reason `logit_core::MetricList` exists and the only reason the list
/// can be re-emitted as one Values part.
#[tokio::test]
async fn a_multi_data_source_list_stays_one_event_with_records_in_wire_order() {
    let raw = read_fixture("multi-value-load", "in");
    let batch = direct_batch(&raw);
    assert_eq!(batch.events.len(), 1, "one Values part is one event");
    let names: Vec<&str> = batch.events[0].metrics.iter().map(name_of).collect();
    assert_eq!(names, vec!["load.load.0", "load.load.1", "load.load.2"]);

    let mut harness = Harness::new().await;
    let (_, decoded) = harness.round_trip(&batch).await;
    assert_eq!(decoded.events.len(), 1);
    assert_eq!(
        decoded.events[0].metrics.iter().map(|m| m.kind.clone()).collect::<Vec<_>>(),
        vec![MetricKind::Gauge(0.05), MetricKind::Gauge(0.15), MetricKind::Gauge(0.25)],
        "the three gauges must come back in the order they went out"
    );
}

/// Normalization 6, called out on its own: the *model* side of a NaN gauge is a
/// `NO_RECORDED_VALUE`-flagged `Gauge(0.0)`, which is what makes the whole-`EventBatch` equality in
/// `the_corpus_round_trips_byte_for_byte` meaningful at all -- a `Gauge(f64::NAN)` could never
/// compare equal to itself.
#[tokio::test]
async fn a_nan_gauge_is_a_flagged_point_on_both_sides_of_the_relay() {
    let raw = read_fixture("nan-gauge", "in");
    let batch = direct_batch(&raw);
    let record = &batch.events[0].metrics[0];
    assert_eq!(record.kind, MetricKind::Gauge(0.0));
    assert!(record.is_no_recorded_value(), "collectd's NaN is the model's NO_RECORDED_VALUE");

    let mut harness = Harness::new().await;
    let (captured, decoded) = harness.round_trip(&batch).await;
    // The re-emitted NaN is this platform's canonical one, not the input's payload bits.
    let value_bytes = &captured[0][captured[0].len() - 8..];
    assert_eq!(value_bytes, f64::NAN.to_le_bytes(), "the NaN payload bits canonicalize");
    assert_ne!(value_bytes, 0xFFF8_0000_0000_0001u64.to_le_bytes(), "...and are not the input's");
    assert!(decoded.events[0].metrics[0].is_no_recorded_value());
}

/// Normalization 2, and the half of it that matters operationally: a `cdtime_t` with live
/// sub-second bits may move one tick on the **first** hop, and must then be a fixed point. The
/// second hop is asserted byte-identical to the first, not merely close.
#[tokio::test]
async fn a_sub_second_time_moves_at_most_one_tick_and_is_then_stable() {
    let raw = read_fixture("sub-second-time", "in");
    let batch = direct_batch(&raw);
    let mut harness = Harness::new().await;

    let (first, decoded_once) = harness.round_trip(&batch).await;
    assert_eq!(first[0], expected_bytes("sub-second-time", &raw));

    let (second, decoded_twice) = harness.round_trip(&decoded_once).await;
    assert_eq!(
        second[0], first[0],
        "the second hop must be byte-identical to the first -- a tick that kept drifting would not \
         be a permitted normalization, it would be a broken conversion"
    );
    assert_eq!(decoded_twice, decoded_once, "and the model side must be a fixed point too");

    // The one-tick tolerance itself: the `TimeHR` part's payload is the eight bytes after its
    // four-byte header, and this fixture writes it as the datagram's second part.
    let wire_time = |bytes: &[u8]| {
        let at = 4 + b"web-1".len() + 1 + 4; // Host part, then the TimeHR header.
        u64::from_be_bytes(bytes[at..at + 8].try_into().unwrap())
    };
    let original = TIME_HR | SUB_SECOND_TICKS;
    let moved = wire_time(&first[0]);
    assert!(
        moved.abs_diff(original) <= 1,
        "a TimeHR may move at most one 2^-30 s tick on the first hop, got {moved} from {original}"
    );
    assert_ne!(
        moved, original,
        "SUB_SECOND_TICKS is chosen precisely because it *does* move -- if this ever stops being \
         true the fixture has quietly stopped exercising normalization 2"
    );
}

/// Normalization 3's other half, which no single-datagram fixture can reach: 30 value lists that
/// arrived in **one** 1412-byte datagram leave as several, because the sink's own
/// `max_packet_bytes` -- not the sender's -- decides where the boundaries fall. Structural rather
/// than byte-for-byte on purpose: the boundaries are exactly what this case lets move.
#[tokio::test]
async fn thirty_lists_in_one_datagram_repack_at_a_lower_cap() {
    let raw = read_fixture("repacked-at-1024", "in");
    assert!(
        raw.len() <= DEFAULT_MAX_PACKET_BYTES,
        "the input is one legal default-capped datagram"
    );
    let batch = direct_batch(&raw);
    assert_eq!(batch.events.len(), 30);

    let mut harness = Harness::new().await;
    let (captured, decoded) =
        harness.round_trip_with(&batch, |sink| sink.with_max_packet_bytes(1024)).await;

    assert!(
        captured.len() >= 2,
        "30 lists cannot fit one 1024-byte datagram, got {}",
        captured.len()
    );
    for (index, datagram) in captured.iter().enumerate() {
        assert!(
            datagram.len() <= 1024,
            "datagram {index} is {} bytes, over the configured cap",
            datagram.len()
        );
    }
    // Every list survives the re-packing, identity and all -- the point of re-encoding a list that
    // lands at a fresh packet's start rather than letting its elided identity leak across the
    // boundary.
    assert_eq!(
        decoded, batch,
        "the whole batch must survive re-packing, however the datagrams were cut"
    );
}

// -- decode only ------------------------------------------------------------------------------------

/// A listener whose decoder-side diagnostics land in a [`Registry`] this test can read -- the
/// `with_diagnostics` half `CollectdInput` propagates into the decoder via `map_decoder`.
async fn diagnostic_harness() -> (Harness, Arc<Registry>) {
    let registry = Registry::new();
    let diag = Diagnostics::new("collectd_in").with_telemetry(registry.telemetry_for(
        "in/diag",
        "collectd_in",
        "input",
    ));
    (Harness::with_diagnostics(diag).await, registry)
}

/// A `0x0210` Encryption part stops the walk where it sits: the list in front of it is a genuine,
/// already-decoded metric and is kept; the list behind it is ciphertext this codec holds no key for
/// and must never appear.
#[tokio::test]
async fn an_encryption_part_drops_the_datagram_tail_and_is_counted() {
    let (mut harness, registry) = diagnostic_harness().await;
    harness.send_raw(&read_fixture("encrypted", "in")).await;
    let batch = harness.drain_decoded().await;

    assert_eq!(batch.events.len(), 1, "only the plaintext list before the Encryption part");
    assert_eq!(batch.events[0].metrics[0].kind, MetricKind::Gauge(3600.0));
    assert!(
        counted(&registry, "logit.component.diagnostics", ("key", "encrypted_packet_dropped")),
        "the dropped tail must be reported, not silent"
    );
}

/// Normalization 7 from the decode side: a list with no `Time`/`TimeHR` part at all borrows the
/// datagram's receipt time. collectd's own receiver rejects such a list outright; `logit` observes
/// rather than polices, exactly as every other listener in the tree stamps receipt time.
#[tokio::test]
async fn a_list_with_no_time_part_is_stamped_with_receipt_time() {
    let harness = Harness::new().await;
    let before =
        std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
            as i64;
    harness.send_raw(&read_fixture("no-time", "in")).await;
    let mut harness = harness;
    let batch = harness.drain_decoded().await;
    let after =
        std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
            as i64;

    assert_eq!(batch.events.len(), 1);
    let timestamp = batch.events[0].timestamp;
    assert!(
        (before..=after).contains(&timestamp),
        "expected a receipt-time stamp in {before}..={after}, got {timestamp}"
    );
}

/// A malformed part behind an already-decoded list keeps the list and abandons the rest --
/// per-list isolation, the same stance `statsd_in` takes per line. Reported as `bad_part`, not the
/// shared listener's whole-datagram `bad_datagram`.
#[tokio::test]
async fn a_truncated_values_part_keeps_the_lists_already_decoded_and_is_counted() {
    let (mut harness, registry) = diagnostic_harness().await;
    harness.send_raw(&read_fixture("truncated-values", "in")).await;
    let batch = harness.drain_decoded().await;

    assert_eq!(batch.events.len(), 1, "the well-formed list in front of the bad part survives");
    assert_eq!(batch.events[0].metrics[0].kind, MetricKind::Gauge(0.5));
    assert!(counted(&registry, "logit.component.diagnostics", ("key", "bad_part")));
}

/// An empty `Host` part clears the sticky host, so the list behind it has no identity to dispatch
/// against and is skipped -- a well-formed part carrying an unusable list, which is a skip rather
/// than a malformed-datagram abort.
#[tokio::test]
async fn a_list_with_a_cleared_host_is_skipped_and_counted() {
    let (mut harness, registry) = diagnostic_harness().await;
    harness.send_raw(&read_fixture("incomplete-identity", "in")).await;
    let batch = harness.drain_decoded().await;

    assert_eq!(batch.events.len(), 1, "only the list that still had a host");
    assert_eq!(batch.events[0].metrics[0].kind, MetricKind::Gauge(0.5));
    assert!(counted(&registry, "logit.component.diagnostics", ("key", "incomplete_identity")));
}

// -- cross protocol: `statsd_in -> collectd_out` -----------------------------------------------------

/// A live `statsd_in` feeding a live `collectd_out`, the way `statsd_round_trip.rs` drives its own
/// listener: raw statsd bytes over a real socket, decoded by the real `StatsdInput`, then handed to
/// a `collectd_out` whose capture socket and `collectd_in` are the harness's.
struct CrossHarness {
    collectd: Harness,
    statsd_addr: SocketAddr,
    statsd_rx: mpsc::Receiver<Delivered>,
}

impl CrossHarness {
    async fn new() -> Self {
        let collectd = Harness::new().await;
        let mut input = StatsdInput::new("127.0.0.1:0");
        input.bind().await.expect("binding the statsd_in listener");
        let statsd_addr = input.local_addr().expect("bind() should leave a real address behind");
        let (tx, statsd_rx) = mpsc::channel(16);
        let sink = Fanout::new(vec![tx]);
        tokio::spawn(async move {
            let _ = input.run(sink).await;
        });
        Self { collectd, statsd_addr, statsd_rx }
    }

    /// The `EventBatch` a live `statsd_in` decodes from `line`.
    async fn statsd_decode(&mut self, line: &[u8]) -> EventBatch {
        let sender =
            UdpSocket::bind("127.0.0.1:0").await.expect("binding an ephemeral sender socket");
        sender.send_to(line, self.statsd_addr).await.expect("sending the statsd line");
        let delivered = tokio::time::timeout(FIRST, self.statsd_rx.recv())
            .await
            .expect("statsd_in should decode and forward the batch")
            .expect("the Fanout channel should not have closed");
        logit_pipeline::unwrap_batch(delivered)
    }
}

/// A statsd counter carries no collectd identity at all, so it takes the encoder's **fallback**
/// path: plugin = the metric name up to its first `.`, type = the stock single-data-source
/// `types.db` name for its kind. `hits:5|c` is a *delta, monotonic* `Sum`, which is precisely what
/// collectd's ABSOLUTE means.
#[tokio::test]
async fn a_statsd_counter_relays_as_one_absolute_list() {
    let mut cross = CrossHarness::new().await;
    let batch = cross.statsd_decode(b"hits:5|c").await;
    assert_eq!(batch.events.len(), 1);

    let (captured, decoded) = cross
        .collectd
        .round_trip_with(&batch, |sink| {
            // `with_encoder` re-applies this sink's own cap, diagnostics and telemetry on top of
            // whatever it is handed, so a hostname-only encoder does not silently revert the
            // datagram cap to `CollectdEncoder::new()`'s uncapped default.
            sink.with_encoder(CollectdEncoder::new().with_hostname("relay-host"))
        })
        .await;
    assert_eq!(captured.len(), 1);

    assert_eq!(decoded.events.len(), 1, "one record, one single-data-source value list");
    let event = &decoded.events[0];
    assert_eq!(attr(event, ATTR_HOST), Some(Value::from("relay-host")));
    assert_eq!(attr(event, ATTR_PLUGIN), Some(Value::from("hits")));
    assert_eq!(attr(event, ATTR_TYPE), Some(Value::from("absolute")));
    assert_eq!(attr(event, ATTR_PLUGIN_INSTANCE), None);
    assert_eq!(attr(event, ATTR_TYPE_INSTANCE), None, "`hits` has no dot to split an instance off");
    assert_eq!(name_of(&event.metrics[0]), "hits.absolute");
    match &event.metrics[0].kind {
        MetricKind::Sum(sum) => {
            assert_eq!(sum.value, 5.0);
            assert_eq!(sum.temporality, logit_core::Temporality::Delta);
            assert!(sum.monotonic);
        }
        other => panic!("expected a delta monotonic Sum, got {other:?}"),
    }
}

/// `@0.3` extrapolates `2` to `6.666…` at decode time, and collectd's COUNTER/DERIVE/ABSOLUTE are
/// all integral: both `6` and `7` are numbers nobody sent, so the list is dropped and counted
/// rather than rounded. Nothing reaches the wire at all, so this asserts the sink's own counter --
/// there is no datagram to capture.
#[tokio::test]
async fn a_sampled_statsd_counter_with_a_fractional_value_is_dropped_and_counted() {
    let mut cross = CrossHarness::new().await;
    let batch = cross.statsd_decode(b"page.views:2|c|@0.3").await;
    let value = match &batch.events[0].metrics[0].kind {
        MetricKind::Sum(sum) => sum.value,
        other => panic!("expected a Sum, got {other:?}"),
    };
    assert!((value - 6.666_666_666_666_667).abs() < 1e-9, "the fixture's premise: {value}");

    let registry = Registry::new();
    let mut sink = CollectdOutput::udp(cross.collectd.capture_addr.to_string())
        .unwrap()
        .with_telemetry(registry.telemetry_for("out", "collectd_out", "sink"))
        .with_encoder(CollectdEncoder::new().with_hostname("relay-host"));
    sink.send(&batch).await.expect("a fully-dropped batch is not a send error");

    assert!(
        counted(&registry, "logit.output.metrics.skipped", ("reason", "unencodable_value")),
        "the drop must be counted, not silent"
    );
}

/// collectd has no tag concept at all, so a DogStatsD tag is dropped and counted on the way out --
/// once per attribute per event. The gauge itself relays intact.
#[tokio::test]
async fn a_tagged_statsd_gauge_relays_as_a_gauge_with_its_tag_counted_away() {
    let mut cross = CrossHarness::new().await;
    let batch = cross.statsd_decode(b"temp:21.5|g|#env:prod").await;
    assert_eq!(batch.events[0].attributes.get("env").and_then(Value::as_str), Some("prod"));

    let registry = Registry::new();
    let telemetry = registry.telemetry_for("out", "collectd_out", "sink");
    let (captured, decoded) = cross
        .collectd
        .round_trip_with(&batch, |sink| {
            // Deliberately telemetry-then-encoder, the builder order that used to drop the handle
            // the codec's own counters go through (`CollectdOutput::with_encoder`'s doc comment).
            sink.with_telemetry(telemetry.clone())
                .with_encoder(CollectdEncoder::new().with_hostname("relay-host"))
        })
        .await;
    assert_eq!(captured.len(), 1);

    let event = &decoded.events[0];
    assert_eq!(attr(event, ATTR_PLUGIN), Some(Value::from("temp")));
    assert_eq!(attr(event, ATTR_TYPE), Some(Value::from("gauge")));
    assert_eq!(name_of(&event.metrics[0]), "temp.gauge");
    assert_eq!(event.metrics[0].kind, MetricKind::Gauge(21.5));
    assert_eq!(event.attributes.get("env"), None, "collectd has no wire form for a tag");

    // Both sinks share one `Telemetry`, so the tag is counted once per sink -- one for the capture
    // leg, one for the live-input leg.
    let events = registry.drain(0);
    assert_eq!(
        metric_sum(&events, "logit.output.tags.dropped", ("reason", "no_wire_form")),
        2.0,
        "`env` has no wire form, and is counted once on each of the two sinks this case sends \
         through"
    );
}

// -- `collectd_in -> aggregate -> collectd_out` --------------------------------------------------------

/// A COUNTER and a DERIVE both decode to a **cumulative** `Sum`, which `aggregate` forwards
/// untouched (`passes_through`: re-accumulating a running total would double-count it). So a window
/// in the middle of the relay changes nothing at all -- no re-timestamping, no identity loss -- and
/// the datagram is byte-identical to the one the same fixture produces with no `aggregate` at all.
///
/// The contrast worth naming: ABSOLUTE decodes to a *delta* `Sum` and a GAUGE to a `Gauge`, both of
/// which `aggregate` genuinely absorbs and re-stamps with the flush clock. That is `aggregate`
/// summarizing on purpose, not a relay defect -- and is why `examples/collectd-relay.yaml` has no
/// `aggregate` in it.
#[tokio::test]
async fn collectd_in_aggregate_collectd_out_relay_is_exact_for_cumulative_sums() {
    let raw = read_fixture("if-octets-derive", "in");
    let batch = direct_batch(&raw);
    let mut harness = Harness::new().await;

    // The baseline: the same fixture with no `aggregate` in the middle.
    let (direct, _) = harness.round_trip(&batch).await;

    let mut aggregator = Aggregator::new(Duration::from_secs(10));
    let resource = batch.resource.clone();
    let forwarded: Vec<logit_core::Event> = batch
        .events
        .iter()
        .cloned()
        .filter_map(|event| aggregator.process(&resource, event))
        .collect();
    assert_eq!(
        forwarded.len(),
        batch.events.len(),
        "a cumulative Sum passes straight through aggregate, unabsorbed"
    );
    let windowed = EventBatch { resource, scope: None, events: forwarded };
    assert_eq!(
        windowed, batch,
        "and passes through *unchanged* -- timestamp and identity included"
    );

    let (through_aggregate, decoded) = harness.round_trip(&windowed).await;
    assert_eq!(
        through_aggregate, direct,
        "an aggregate window between the two ends must not change one byte of the relay"
    );
    assert_eq!(decoded, batch);

    // Nothing was absorbed, so there is nothing for the window to flush.
    assert!(
        aggregator.flush(1_800_000_000_000_000_000).is_empty(),
        "a window that absorbed nothing has nothing to emit"
    );
}
