//! `prometheus_in -> prometheus_out` over real sockets. A canned `hyper` server plays the scraped
//! target, serving a fixture's `.in` body under its dialect's `Content-Type`; a bound
//! [`PrometheusInput`] scrapes it into a [`Fanout`], the batch goes into a real [`ExposeOutput`],
//! and a `reqwest` client scrapes that with a chosen `Accept`.
//!
//! The result must equal the fixture's `.expected` body byte for byte. The differences allowed
//! between `.in` and `.expected` are the list under `crates/logit-proto/src/prometheus/mod.rs`'s
//! "Permitted normalizations" heading. Two more are this file's own, applied to the actual output
//! only by [`strip_synthetic_and_placeholder_port`]: the three synthetic families `prometheus_in`
//! adds are excluded by name, and the target's ephemeral `host:port` becomes the literal `{port}`.
//!
//! ## Fixture corpus (`tests/fixtures/prometheus/`)
//!
//! Inputs are the Prometheus exposition-format docs' and the OpenMetrics spec's worked examples
//! (the strings `crates/logit-proto/tests/prometheus_fixed_point.rs` embeds), named
//! `<name>.<in-dialect>.in` with `text` or `om`; the expected body is
//! `<name>.<out-dialect>.expected`. Matching extensions are a same-dialect fixed point, differing
//! ones a dialect change. There is no `SAME AS INPUT` sentinel: the added `instance` label means
//! no output is byte-identical to its input.
//!
//! Each `.expected` file was generated by the real `logit_proto::prometheus` codec (`parse` ->
//! `families_to_events` -> `events_to_families` with an `instance` resource attribute of `{port}`
//! -> `write`), then checked line by line so every difference from its `.in` is a permitted
//! normalization. Metadata-line order is fixed per dialect (OpenMetrics writes `# TYPE` first,
//! text 0.0.4 writes `# HELP` first), as `crates/logit-outputs/src/prometheus.rs`'s
//! `EXPECTED_TEXT` and `EXPECTED_OPENMETRICS` show. The codec's own correctness is
//! `prometheus_fixed_point.rs`'s job; this file proves the real sockets and components compose to
//! the same result.
//!
//! What each fixture exercises beyond ordering, float formatting, and `instance`:
//!
//! - `counter_no_total` (text): the bare `requests` sample gains `_total`; a wire millisecond
//!   timestamp survives unchanged.
//! - `counter_created`, `histogram`, `full_openmetrics` (OM -> OM): `_created`, `# UNIT`,
//!   exemplars, and `info`/`stateset`/`gaugehistogram`/`unknown` all survive when neither leg is
//!   text 0.0.4, so dropping them is dialect-triggered, not unconditional.
//! - `gauge`, `escaped_and_special` (text): `-Inf`/`NaN`/`+Inf` spellings and escaped label values.
//! - `summary` (text): quantile labels sorted.
//! - `untyped_no_type` (text): `# TYPE bare_metric untyped` synthesized for a family with no
//!   metadata line.
//! - `dialect_text_untyped_to_om` (text -> OM): `untyped` becomes `unknown`.
//! - `dialect_om_types_to_text` (OM -> text): `unknown`, `info` (with an `_info`-suffixed sample),
//!   `stateset`, and `gaugehistogram` down-convert, and a counter's `# UNIT`, `_created`, and
//!   exemplar are dropped.

use bytes::Bytes;
use http_body_util::Full;
use hyper::body::Incoming;
use hyper::service::service_fn;
use hyper::{Request, Response};
use hyper_util::rt::TokioIo;
use logit_core::{EventBatch, Registry};
use logit_inputs::internal::InternalInput;
use logit_inputs::prometheus::PrometheusInput;
use logit_inputs::statsd::StatsdInput;
use logit_outputs::prometheus::ExposeOutput;
use logit_pipeline::{Fanout, Input, Output};
use logit_proto::prometheus::text::{self, Dialect};
use logit_transforms::{AggregateTemporality, Aggregator};
use std::convert::Infallible;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::time::Duration;
use tokio::sync::mpsc;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/prometheus")
}

fn read_fixture(name: &str, ext: &str) -> Vec<u8> {
    let path = fixtures_dir().join(format!("{name}.{ext}"));
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

/// The three families `prometheus_in` always synthesizes, excluded from every comparison by name.
const SYNTHETIC_FAMILIES: [&str; 3] = ["up", "scrape_duration_seconds", "scrape_samples_scraped"];

/// Reparses `body` (what a real scrape of `prometheus_out` returned), drops the synthetic
/// families, re-renders, and replaces `target_addr` with the fixtures' `{port}` placeholder. Only
/// the actual output is rewritten; a fixture is never adjusted to match the run.
fn strip_synthetic_and_placeholder_port(
    body: &str,
    dialect: Dialect,
    target_addr: SocketAddr,
) -> String {
    let families = text::parse(body.as_bytes(), dialect)
        .unwrap_or_else(|e| panic!("actual prometheus_out output must parse: {e}\nbody:\n{body}"));
    let filtered: Vec<_> =
        families.into_iter().filter(|f| !SYNTHETIC_FAMILIES.contains(&f.name.as_str())).collect();
    let mut out = Vec::new();
    text::write(&filtered, dialect, &mut out);
    let rendered = String::from_utf8(out).expect("exposition must be utf-8");
    rendered.replace(&target_addr.to_string(), "{port}")
}

/// A scrape target serving one fixed body under one fixed `Content-Type` on every request. A copy
/// of `crates/logit-inputs/src/prometheus.rs`'s `canned_server` test helper, which isn't visible
/// across the crate boundary.
async fn canned_server(body: Bytes, content_type: &'static str) -> SocketAddr {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    tokio::spawn(async move {
        loop {
            let Ok((stream, _)) = listener.accept().await else { return };
            let io = TokioIo::new(stream);
            let body = body.clone();
            tokio::spawn(async move {
                let service = service_fn(move |_req: Request<Incoming>| {
                    let body = body.clone();
                    async move {
                        Ok::<_, Infallible>(
                            Response::builder()
                                .status(200)
                                .header("content-type", content_type)
                                .body(Full::new(body))
                                .unwrap(),
                        )
                    }
                });
                let _ =
                    hyper::server::conn::http1::Builder::new().serve_connection(io, service).await;
            });
        }
    });
    addr
}

/// A `reqwest` client with gzip decoding off, so a body arrives as `prometheus_out` wrote it.
fn http_client() -> reqwest::Client {
    reqwest::Client::builder().no_gzip().build().expect("a default client always builds")
}

/// Scrapes `target_addr` with a bound [`PrometheusInput`] on a 20ms interval, relays the first
/// batch into a fresh [`ExposeOutput`], and returns the body a GET with `accept` gets back, plus
/// `target_addr` (what the caller replaces with `{port}`).
async fn scrape_relay_and_fetch(target_addr: SocketAddr, accept: &str) -> (String, SocketAddr) {
    let mut input = PrometheusInput::new(
        vec![format!("http://{target_addr}/metrics")],
        Duration::from_millis(20),
    );
    let (tx, mut rx) = mpsc::channel(16);
    let sink = Fanout::new(vec![tx]);
    tokio::spawn(async move {
        let _ = input.run(sink).await;
    });

    // `PrometheusInput::run` skips its immediate first tick, so the first scrape lands one full
    // `interval` in; the 2s timeout is well past that.
    let delivered = tokio::time::timeout(Duration::from_secs(2), rx.recv())
        .await
        .expect("prometheus_in should scrape and forward a batch")
        .expect("the Fanout channel should not have closed");
    let batch = logit_pipeline::unwrap_batch(delivered);

    let (body, _addr) = expose_and_fetch(std::slice::from_ref(&batch), accept).await;
    (body, target_addr)
}

/// Binds a fresh [`ExposeOutput`], sends it `batches`, and fetches its exposition with `accept`.
/// Returns the body and the sink's own address, which no caller here uses.
async fn expose_and_fetch(batches: &[EventBatch], accept: &str) -> (String, SocketAddr) {
    let mut output = ExposeOutput::new("127.0.0.1:0");
    output.bind().await.expect("binding prometheus_out");
    let addr = output.local_addr().expect("bind() should leave a real address behind");
    for batch in batches {
        output.send(batch).await.expect("send never fails");
    }

    let client = http_client();
    let response = client
        .get(format!("http://{addr}/metrics"))
        .header("accept", accept)
        .send()
        .await
        .expect("the scrape request should reach prometheus_out");
    assert_eq!(response.status(), 200);
    let body = response.text().await.expect("body should be text");
    (body, addr)
}

const ACCEPT_TEXT: &str = "text/plain";
const ACCEPT_OM: &str = "application/openmetrics-text";

fn dialect_of(ext: &str) -> Dialect {
    match ext {
        "text" => Dialect::Text0_0_4,
        "om" => Dialect::OpenMetrics1_0,
        other => panic!("unknown fixture dialect extension {other:?}"),
    }
}

fn content_type_of(ext: &str) -> &'static str {
    dialect_of(ext).content_type()
}

fn accept_of(ext: &str) -> &'static str {
    match ext {
        "text" => ACCEPT_TEXT,
        "om" => ACCEPT_OM,
        other => panic!("unknown fixture dialect extension {other:?}"),
    }
}

/// Scrapes `name`'s `.{in_ext}.in`, fetches it back in `out_ext`'s dialect, and asserts the
/// result (synthetic families stripped, target port replaced with `{port}`) equals
/// `.{out_ext}.expected` byte for byte.
async fn assert_fixture_round_trips(name: &str, in_ext: &str, out_ext: &str) {
    let body = read_fixture(name, &format!("{in_ext}.in"));
    let target_addr = canned_server(Bytes::from(body), content_type_of(in_ext)).await;
    let (actual_raw, _) = scrape_relay_and_fetch(target_addr, accept_of(out_ext)).await;
    let actual =
        strip_synthetic_and_placeholder_port(&actual_raw, dialect_of(out_ext), target_addr);
    let expected = String::from_utf8(read_fixture(name, &format!("{out_ext}.expected")))
        .expect("fixture must be utf-8");
    assert_eq!(actual, expected, "{name}: {in_ext} -> {out_ext} mismatch");
}

// ---- same-dialect fixed points: text -> text, om -> om ------------------------------------------

#[tokio::test]
async fn counter_without_total_gains_it_and_an_instance_label() {
    assert_fixture_round_trips("counter_no_total", "text", "text").await;
}

#[tokio::test]
async fn counter_with_created_round_trips_in_openmetrics() {
    assert_fixture_round_trips("counter_created", "om", "om").await;
}

#[tokio::test]
async fn gauge_with_negative_infinity_round_trips_in_text() {
    assert_fixture_round_trips("gauge", "text", "text").await;
}

#[tokio::test]
async fn histogram_with_unit_created_and_a_bucket_exemplar_round_trips_in_openmetrics() {
    assert_fixture_round_trips("histogram", "om", "om").await;
}

#[tokio::test]
async fn summary_with_quantiles_round_trips_in_text() {
    assert_fixture_round_trips("summary", "text", "text").await;
}

#[tokio::test]
async fn a_family_with_no_type_metadata_gains_a_synthesized_untyped_type() {
    assert_fixture_round_trips("untyped_no_type", "text", "text").await;
}

#[tokio::test]
async fn escaped_label_values_and_special_floats_round_trip_in_text() {
    assert_fixture_round_trips("escaped_and_special", "text", "text").await;
}

#[tokio::test]
async fn info_stateset_gaugehistogram_unknown_and_a_total_exemplar_round_trip_in_openmetrics() {
    assert_fixture_round_trips("full_openmetrics", "om", "om").await;
}

// ---- dialect changes: cross-dialect family-type substitution ------------------------------------

#[tokio::test]
async fn a_text_untyped_family_becomes_unknown_when_served_as_openmetrics() {
    assert_fixture_round_trips("dialect_text_untyped_to_om", "text", "om").await;
}

#[tokio::test]
async fn openmetrics_only_types_down_convert_when_served_as_text() {
    assert_fixture_round_trips("dialect_om_types_to_text", "om", "text").await;
}

// ---- pipeline cases: real components, no fixtures -----------------------------------------------

/// `statsd_in -> aggregate(temporality: cumulative) -> prometheus_out`: two `hits:1|c` datagrams
/// become one `hits_total 2` plus an OpenMetrics `_created` line, per ADR
/// `prometheus-scrape-and-exposition`'s "Temporality is `aggregate`'s job" section.
#[tokio::test]
async fn statsd_through_cumulative_aggregate_renders_a_cumulative_counter_with_created() {
    let mut input = StatsdInput::new("127.0.0.1:0");
    input.bind().await.expect("binding statsd_in");
    let addr = input.local_addr().expect("bind() should leave a real address behind");
    let (tx, mut rx) = mpsc::channel(16);
    let sink = Fanout::new(vec![tx]);
    tokio::spawn(async move {
        let _ = input.run(sink).await;
    });

    let sender = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
    sender.send_to(b"hits:1|c", addr).await.expect("send should reach statsd_in");
    sender.send_to(b"hits:1|c", addr).await.expect("send should reach statsd_in");

    let mut aggregator = Aggregator::new(Duration::from_secs(3600))
        .with_temporality(AggregateTemporality::Cumulative)
        .with_series_retention(5, 10_000);

    // The default 100ms `batch_flush_interval` may coalesce both datagrams into one batch, so
    // this counts events, not batches.
    let mut absorbed_events = 0;
    while absorbed_events < 2 {
        let delivered = tokio::time::timeout(Duration::from_secs(2), rx.recv())
            .await
            .expect("statsd_in should forward both increments")
            .expect("the Fanout channel should not have closed");
        let batch = logit_pipeline::unwrap_batch(delivered);
        let resource = batch.resource.clone();
        for mut event in batch.events {
            absorbed_events += 1;
            let forwarded = aggregator.process(&resource, &mut event);
            assert!(!forwarded, "a delta Sum under cumulative temporality must be absorbed");
        }
    }

    let flushed = aggregator.flush(1_700_000_000_000_000_000);
    assert!(!flushed.is_empty(), "two absorbed increments must produce a flushed batch");
    let batches: Vec<EventBatch> = flushed
        .into_iter()
        .map(|(resource, scope, events)| EventBatch {
            resource,
            scope,
            events: events.into_iter().map(|(event, _links)| event).collect(),
        })
        .collect();

    let (body, _addr) = expose_and_fetch(&batches, ACCEPT_OM).await;
    assert!(
        body.contains("hits_total 2"),
        "expected a cumulative hits_total 2 sample, got:\n{body}"
    );
    // `hits_created` must hold a real unix-seconds timestamp: cumulative temporality stamps
    // `start_timestamp` from the series' first-seen wall-clock time, so a value below 1.6e9
    // (2020-09-13) means the wrong field, or none, was rendered.
    let created_line = body
        .lines()
        .find(|line| line.starts_with("hits_created"))
        .unwrap_or_else(|| panic!("expected a hits_created line, got:\n{body}"));
    let created_value: f64 = created_line
        .split_whitespace()
        .nth(1)
        .unwrap_or_else(|| panic!("hits_created line has no value: {created_line:?}"))
        .parse()
        .unwrap_or_else(|e| panic!("hits_created value should parse as a float: {e}"));
    assert!(
        created_value > 1.6e9,
        "hits_created {created_value} is not a plausible unix-seconds timestamp, in:\n{body}"
    );
}

/// `internal -> aggregate(temporality: cumulative) -> prometheus_out`: a `logit.component.*`
/// self-telemetry counter renders as an ordinary counter family, so `prometheus_out` is one more
/// sink the graph feeds, not a second telemetry representation. See
/// [ADR `internal-telemetry-as-pipeline-events`](../../../docs/adr/internal-telemetry-as-pipeline-events.md)'s
/// "Amendment: a `prometheus_out` sink is not the rejected scrape endpoint" section.
#[tokio::test]
async fn internal_telemetry_through_cumulative_aggregate_renders_a_logit_component_counter() {
    let registry = Registry::new();
    let telemetry = registry.telemetry_for("probe", "statsd_in", "listener");
    telemetry.count("logit.component.batches.sent", 3.0, &[]);

    let mut input = InternalInput::new(Duration::from_millis(20), registry);
    let (tx, mut rx) = mpsc::channel(16);
    let sink = Fanout::new(vec![tx]);
    tokio::spawn(async move {
        let _ = input.run(sink).await;
    });

    let delivered = tokio::time::timeout(Duration::from_secs(2), rx.recv())
        .await
        .expect("internal should drain and forward a batch")
        .expect("the Fanout channel should not have closed");
    let batch = logit_pipeline::unwrap_batch(delivered);

    let mut aggregator = Aggregator::new(Duration::from_secs(3600))
        .with_temporality(AggregateTemporality::Cumulative)
        .with_series_retention(5, 10_000);

    let mut passthrough = Vec::new();
    for mut event in batch.events {
        if aggregator.process(&batch.resource, &mut event) {
            passthrough.push(event);
        }
    }

    let flushed = aggregator.flush(1_700_000_000_000_000_000);
    let mut batches: Vec<EventBatch> = flushed
        .into_iter()
        .map(|(resource, scope, events)| EventBatch {
            resource,
            scope,
            events: events.into_iter().map(|(event, _links)| event).collect(),
        })
        .collect();
    if !passthrough.is_empty() {
        batches.push(EventBatch {
            resource: batch.resource.clone(),
            scope: batch.scope.clone(),
            events: passthrough,
        });
    }

    let (body, _addr) = expose_and_fetch(&batches, ACCEPT_TEXT).await;
    assert!(
        body.contains("logit_component_batches_sent_total"),
        "expected at least one logit_component_* counter family, got:\n{body}"
    );
}

/// `aggregate -> prometheus_out`: a series keeps its first record's `description`, which the
/// exposition renders as `# HELP`, on both the tumbling (gauge, no retention) and the retained
/// (cumulative counter) flush paths.
#[tokio::test]
async fn aggregate_carries_the_first_records_description_into_help() {
    use logit_core::interner::intern;
    use logit_core::{AttrMap, Event, MetricKind, MetricRecord, Resource};
    use std::sync::Arc;

    let record = |name: &str, kind: MetricKind, description: &str| {
        let mut record = MetricRecord::new(intern(name), kind);
        record.description = Some(intern(description));
        record
    };
    let resource = Arc::new(Resource::default());
    let mut tumbling = Aggregator::new(Duration::from_secs(10));
    let mut retained = Aggregator::new(Duration::from_secs(10))
        .with_temporality(AggregateTemporality::Cumulative)
        .with_series_retention(5, 100);
    for (i, description) in ["Queue depth.", "A later description."].into_iter().enumerate() {
        let gauge = record("depth", MetricKind::Gauge(i as f64), description);
        assert!(!tumbling.process(&resource, &mut Event::metric(0, AttrMap::new(), gauge)));
    }
    let hits = record("hits", MetricKind::counter(1.0), "Requests served.");
    assert!(!retained.process(&resource, &mut Event::metric(0, AttrMap::new(), hits)));

    let now = 1_700_000_000_000_000_000;
    let batches: Vec<EventBatch> = [tumbling.flush(now), retained.flush(now)]
        .into_iter()
        .flatten()
        .map(|(resource, scope, events)| EventBatch {
            resource,
            scope,
            events: events.into_iter().map(|(event, _links)| event).collect(),
        })
        .collect();

    let (body, _addr) = expose_and_fetch(&batches, ACCEPT_TEXT).await;
    assert!(body.contains("# HELP depth Queue depth."), "the first record's, got:\n{body}");
    assert!(body.contains("# HELP hits_total Requests served."), "got:\n{body}");
}

/// `aggregate -> prometheus_out`: a cumulative series the cardinality cap evicts and a later event
/// with source timestamp `0` re-creates renders `_created` as the start of the window it reopened
/// in, not `0` and not before the point it replaces.
#[tokio::test]
async fn a_re_created_cumulative_series_renders_created_at_its_window_start() {
    use logit_core::interner::intern;
    use logit_core::{AttrMap, Event, MetricKind, MetricRecord, Resource};
    use std::sync::Arc;

    let resource = Arc::new(Resource::default());
    // A cap of 1 keeps `anchor`, opened first, and evicts `hits` at every flush.
    let mut aggregator = Aggregator::new(Duration::from_secs(10))
        .with_temporality(AggregateTemporality::Cumulative)
        .with_series_retention(5, 1);
    let feed = |aggregator: &mut Aggregator, timestamp: i64| {
        for name in ["anchor", "hits"] {
            let record = MetricRecord::new(intern(name), MetricKind::counter(1.0));
            let mut event = Event::metric(timestamp, AttrMap::new(), record);
            assert!(!aggregator.process(&resource, &mut event));
        }
    };
    let first_flush = 1_700_000_000_000_000_000;
    feed(&mut aggregator, first_flush - 1);
    aggregator.flush(first_flush);
    feed(&mut aggregator, 0);
    let batches: Vec<EventBatch> = aggregator
        .flush(first_flush + 10_000_000_000)
        .into_iter()
        .map(|(resource, scope, events)| EventBatch {
            resource,
            scope,
            events: events.into_iter().map(|(event, _links)| event).collect(),
        })
        .collect();

    let (body, _addr) = expose_and_fetch(&batches, ACCEPT_OM).await;
    assert!(body.contains("hits_total 1"), "the re-created series restarts, got:\n{body}");
    let created: f64 = body
        .lines()
        .find_map(|line| line.strip_prefix("hits_created "))
        .unwrap_or_else(|| panic!("expected a hits_created line, got:\n{body}"))
        .trim()
        .parse()
        .expect("hits_created parses as a float");
    assert_eq!(created, 1.7e9, "the first flush's clock, in:\n{body}");
}
