//! `prometheus_in -> prometheus_out` round trip over real sockets -- the Prometheus counterpart to
//! `syslog_round_trip.rs`/`otlp_round_trip.rs`. A canned `hyper` server plays the scraped target
//! (serving a fixture's `.in` body under the right `Content-Type`); a real, bound [`PrometheusInput`]
//! scrapes it and forwards through a [`Fanout`] into a real [`PrometheusOutput`], which a `reqwest`
//! client then scrapes in turn with a chosen `Accept`. `docs/plans/prometheus-scrape-and-exposition.md`'s
//! W5 workstream.
//!
//! ## Permitted normalizations (recorded here, and in `docs/adr/prometheus-scrape-and-exposition.md`'s
//! "Permitted normalizations for this pair" section, which this list transcribes)
//!
//! 1. **Family/series reordering.** Families sorted by name, series within a family sorted by
//!    label set.
//! 2. **Label reordering**, sorted by rendered (post-sanitization) name.
//! 3. **Float formatting**: shortest round-trip representation (`1.0` renders as `1`).
//! 4. **`# TYPE x untyped` synthesized** for a family that arrived with no `# TYPE` metadata at
//!    all. Exercised by `untyped_no_type`.
//! 5. **`_created`, `# UNIT`, and exemplars dropped** when the *output* dialect is text 0.0.4 --
//!    none of the three has a text 0.0.4 wire representation.
//! 6. **`# EOF` presence**: written only when the output dialect is OpenMetrics.
//! 7. **Blank lines and non-`HELP`/`TYPE`/`UNIT` comments dropped.**
//! 8. **An `instance` label is added**, `host:port` of the scraped target -- exactly as
//!    Prometheus's own scrape does. Present on every fixture's expected output as the literal
//!    placeholder `{port}` (see "Fixture corpus" below).
//! 9. **A counter sample name gains a `_total` suffix if it lacked one**, in either dialect.
//!    Exercised by `counter_no_total`.
//! 10. **A cross-dialect family-type substitution** when the output dialect lacks the wire type
//!     the model attribute names (`untyped`<->`unknown`, `info`/`stateset`/`gaugehistogram`
//!     down-converted on text egress, `_info` re-appended on OM egress). Exercised by
//!     `dialect_text_untyped_to_om` and `dialect_om_types_to_text`.
//! 11. **The three synthetic families `prometheus_in` always adds** (`up`,
//!     `scrape_duration_seconds`, `scrape_samples_scraped`) are excluded from every comparison in
//!     this file by name, not asserted equal at all -- see [`strip_synthetic_and_placeholder_port`].
//!
//! ## Fixture corpus (`tests/fixtures/prometheus/`)
//!
//! One input body per case, drawn from the Prometheus exposition-format docs' and the OpenMetrics
//! spec's own worked examples (the same strings `crates/logit-proto/tests/prometheus_fixed_point.rs`
//! already embeds), named `<name>.<in-dialect>.in` (`text` or `om`), and one expected exposition
//! body per requested output dialect, named `<name>.<out-dialect>.expected`. For a same-dialect
//! fixed point the two extensions match (`gauge.text.in` / `gauge.text.expected`); for a
//! dialect-change case they differ (`dialect_text_untyped_to_om.text.in` /
//! `dialect_text_untyped_to_om.om.expected`), exercising normalization 10 above. Every `.expected`
//! file carries the literal placeholder `{port}` wherever the real test substitutes the scraped
//! target's actual ephemeral `instance` value (normalization 8) -- there is no `SAME AS INPUT`
//! sentinel in this corpus, since the added `instance` label means no fixture is ever byte-identical
//! to its own input, unlike `syslog_round_trip.rs`'s corpus.
//!
//! Each `.expected` file was generated by running the real `logit_proto::prometheus` codec
//! (`parse` -> `families_to_events` -> `events_to_families` with an injected `instance` resource
//! attribute of literally `{port}` -> `write`) rather than hand-computed, so it is correct against
//! the same codec `crates/logit-proto/tests/prometheus_fixed_point.rs` already proves fixed-point
//! and grammar-fuzzed -- this file's job is to prove the *real sockets and components* compose to
//! the identical result, not to re-litigate the codec's own correctness.

use bytes::Bytes;
use http_body_util::Full;
use hyper::body::Incoming;
use hyper::service::service_fn;
use hyper::{Request, Response};
use hyper_util::rt::TokioIo;
use logit_core::{EventBatch, Registry};
use logit_inputs::internal::InternalInput;
use logit_inputs::prometheus::PrometheusInput;
use logit_inputs::statsd::StatsdInput;
use logit_outputs::prometheus::PrometheusOutput;
use logit_pipeline::{Fanout, Input, Output};
use logit_proto::prometheus::text::{self, Dialect};
use logit_transforms::{AggregateTemporality, Aggregator};
use std::convert::Infallible;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::time::Duration;
use tokio::sync::mpsc;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/prometheus")
}

fn read_fixture(name: &str, ext: &str) -> Vec<u8> {
    let path = fixtures_dir().join(format!("{name}.{ext}"));
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()))
}

/// The three families `prometheus_in` always synthesizes -- excluded from every comparison in this
/// file by name (permitted normalization 11 above), never asserted equal at all.
const SYNTHETIC_FAMILIES: [&str; 3] = ["up", "scrape_duration_seconds", "scrape_samples_scraped"];

/// Reparses `body` (the bytes a real scrape of `prometheus_out` actually returned), drops the three
/// synthetic families, re-renders, then substitutes `target_addr`'s literal `host:port` with the
/// placeholder `{port}` the fixture files use -- the module doc's normalizations 8 and 11, applied
/// to the *actual* output before comparing against `.expected` (never the other way around: the
/// fixture is never mutated to match the run).
fn strip_synthetic_and_placeholder_port(
    body: &str,
    dialect: Dialect,
    target_addr: SocketAddr,
) -> String {
    let families = text::parse(body.as_bytes(), dialect)
        .unwrap_or_else(|e| panic!("actual prometheus_out output must parse: {e}\nbody:\n{body}"));
    let filtered: Vec<_> =
        families.into_iter().filter(|f| !SYNTHETIC_FAMILIES.contains(&f.name.as_str())).collect();
    let mut out = Vec::new();
    text::write(&filtered, dialect, &mut out);
    let rendered = String::from_utf8(out).expect("exposition must be utf-8");
    rendered.replace(&target_addr.to_string(), "{port}")
}

/// What a canned connection serves: one fixed body under one fixed `Content-Type`, forever -- the
/// scraped target this file's fixed-point cases pretend to be. Modeled on
/// `crates/logit-inputs/src/prometheus.rs`'s own `canned_server` test helper (same `hyper`
/// server-side stack), duplicated rather than shared across the crate boundary, the same reasoning
/// `otlp_round_trip.rs`'s own module doc gives for living in `logit-cli` at all.
async fn canned_server(body: Bytes, content_type: &'static str) -> SocketAddr {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    tokio::spawn(async move {
        loop {
            let Ok((stream, _)) = listener.accept().await else { return };
            let io = TokioIo::new(stream);
            let body = body.clone();
            tokio::spawn(async move {
                let service = service_fn(move |_req: Request<Incoming>| {
                    let body = body.clone();
                    async move {
                        Ok::<_, Infallible>(
                            Response::builder()
                                .status(200)
                                .header("content-type", content_type)
                                .body(Full::new(body))
                                .unwrap(),
                        )
                    }
                });
                let _ =
                    hyper::server::conn::http1::Builder::new().serve_connection(io, service).await;
            });
        }
    });
    addr
}

/// A plain `reqwest` client with gzip transparently disabled -- a gzipped body should arrive
/// exactly as `prometheus_out` wrote it, not silently inflated by the client, matching
/// `crates/logit-outputs/src/prometheus.rs`'s own test helper.
fn http_client() -> reqwest::Client {
    reqwest::Client::builder().no_gzip().build().expect("a default client always builds")
}

/// Scrapes `target_addr` (a [`canned_server`]) with a real, bound [`PrometheusInput`] on a very
/// short interval, waits for the one `EventBatch` it forwards through a bare [`Fanout`], then feeds
/// that batch into a fresh [`PrometheusOutput`] and returns the exposition body a real `reqwest` GET
/// against it gets back for `accept`, alongside `target_addr` itself (what the caller substitutes
/// for `{port}`).
async fn scrape_relay_and_fetch(target_addr: SocketAddr, accept: &str) -> (String, SocketAddr) {
    let mut input = PrometheusInput::new(
        vec![format!("http://{target_addr}/metrics")],
        Duration::from_millis(20),
    );
    let (tx, mut rx) = mpsc::channel(16);
    let sink = Fanout::new(vec![tx]);
    tokio::spawn(async move {
        let _ = input.run(sink).await;
    });

    // `PrometheusInput::run` swallows its first (immediate) tick, so the first real scrape lands
    // after one full `interval` -- a generous timeout well past that single 20ms wait.
    let delivered = tokio::time::timeout(Duration::from_secs(2), rx.recv())
        .await
        .expect("prometheus_in should scrape and forward a batch")
        .expect("the Fanout channel should not have closed");
    let batch = logit_pipeline::unwrap_batch(delivered);

    let (body, _addr) = expose_and_fetch(std::slice::from_ref(&batch), accept).await;
    (body, target_addr)
}

/// Binds a fresh [`PrometheusOutput`], sends every batch in `batches` into it, then fetches its
/// exposition with `accept`. Returns the response body and the sink's own bound address (unused by
/// the fixed-point cases, which care about the *target's* address instead -- see
/// [`scrape_relay_and_fetch`]; the pipeline cases below use this directly and ignore the target
/// address entirely).
async fn expose_and_fetch(batches: &[EventBatch], accept: &str) -> (String, SocketAddr) {
    let mut output = PrometheusOutput::new("127.0.0.1:0");
    output.bind().await.expect("binding prometheus_out");
    let addr = output.local_addr().expect("bind() should leave a real address behind");
    for batch in batches {
        output.send(batch).await.expect("send never fails");
    }

    let client = http_client();
    let response = client
        .get(format!("http://{addr}/metrics"))
        .header("accept", accept)
        .send()
        .await
        .expect("the scrape request should reach prometheus_out");
    assert_eq!(response.status(), 200);
    let body = response.text().await.expect("body should be text");
    (body, addr)
}

const ACCEPT_TEXT: &str = "text/plain";
const ACCEPT_OM: &str = "application/openmetrics-text";

fn dialect_of(ext: &str) -> Dialect {
    match ext {
        "text" => Dialect::Text0_0_4,
        "om" => Dialect::OpenMetrics1_0,
        other => panic!("unknown fixture dialect extension {other:?}"),
    }
}

fn content_type_of(ext: &str) -> &'static str {
    dialect_of(ext).content_type()
}

fn accept_of(ext: &str) -> &'static str {
    match ext {
        "text" => ACCEPT_TEXT,
        "om" => ACCEPT_OM,
        other => panic!("unknown fixture dialect extension {other:?}"),
    }
}

/// One fixed-point or dialect-change case: scrape `name`'s `.{in_ext}.in` body, request the
/// exposition back in `out_ext`'s dialect, and assert the result -- synthetic families stripped,
/// the scraped target's real ephemeral port replaced with `{port}` -- equals `name`'s
/// `.{out_ext}.expected` byte for byte.
async fn assert_fixture_round_trips(name: &str, in_ext: &str, out_ext: &str) {
    let body = read_fixture(name, &format!("{in_ext}.in"));
    let target_addr = canned_server(Bytes::from(body), content_type_of(in_ext)).await;
    let (actual_raw, _) = scrape_relay_and_fetch(target_addr, accept_of(out_ext)).await;
    let actual =
        strip_synthetic_and_placeholder_port(&actual_raw, dialect_of(out_ext), target_addr);
    let expected = String::from_utf8(read_fixture(name, &format!("{out_ext}.expected")))
        .expect("fixture must be utf-8");
    assert_eq!(actual, expected, "{name}: {in_ext} -> {out_ext} mismatch");
}

// ---- text -> text, om -> om: same-dialect fixed points (modulo the module doc's normalizations) -

#[tokio::test]
async fn counter_without_total_gains_it_and_an_instance_label() {
    assert_fixture_round_trips("counter_no_total", "text", "text").await;
}

#[tokio::test]
async fn counter_with_created_round_trips_in_openmetrics() {
    assert_fixture_round_trips("counter_created", "om", "om").await;
}

#[tokio::test]
async fn gauge_with_negative_infinity_round_trips_in_text() {
    assert_fixture_round_trips("gauge", "text", "text").await;
}

#[tokio::test]
async fn histogram_with_unit_created_and_a_bucket_exemplar_round_trips_in_openmetrics() {
    assert_fixture_round_trips("histogram", "om", "om").await;
}

#[tokio::test]
async fn summary_with_quantiles_round_trips_in_text() {
    assert_fixture_round_trips("summary", "text", "text").await;
}

#[tokio::test]
async fn a_family_with_no_type_metadata_gains_a_synthesized_untyped_type() {
    assert_fixture_round_trips("untyped_no_type", "text", "text").await;
}

#[tokio::test]
async fn escaped_label_values_and_special_floats_round_trip_in_text() {
    assert_fixture_round_trips("escaped_and_special", "text", "text").await;
}

#[tokio::test]
async fn info_stateset_gaugehistogram_unknown_and_a_total_exemplar_round_trip_in_openmetrics() {
    assert_fixture_round_trips("full_openmetrics", "om", "om").await;
}

// ---- dialect-change cases: cross-dialect family-type substitution (normalization 10) -----------

#[tokio::test]
async fn a_text_untyped_family_becomes_unknown_when_served_as_openmetrics() {
    assert_fixture_round_trips("dialect_text_untyped_to_om", "text", "om").await;
}

#[tokio::test]
async fn openmetrics_only_types_down_convert_when_served_as_text() {
    assert_fixture_round_trips("dialect_om_types_to_text", "om", "text").await;
}

// ---- pipeline cases: real components, no fixtures -----------------------------------------------

/// `statsd_in -> aggregate(temporality: cumulative) -> prometheus_out`: two `hits:1|c` datagrams
/// absorb into one cumulative counter, which `prometheus_out` renders as `hits_total 2` plus a
/// `_created` line (OpenMetrics only) -- the ADR's "Temporality is `aggregate`'s job" section's own
/// worked example.
#[tokio::test]
async fn statsd_through_cumulative_aggregate_renders_a_cumulative_counter_with_created() {
    // Bind-drop-rebind: `StatsdInput` exposes no `local_addr()` accessor (its `UdpListener` is
    // private), so an ephemeral port is reserved with a throwaway socket first, the same idiom
    // `otlp_round_trip.rs`'s `ephemeral_addr()` uses for TCP.
    let probe = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
    let addr = probe.local_addr().unwrap();
    drop(probe);

    let mut input = StatsdInput::new(addr.to_string());
    input.bind().await.expect("binding statsd_in");
    let (tx, mut rx) = mpsc::channel(16);
    let sink = Fanout::new(vec![tx]);
    tokio::spawn(async move {
        let _ = input.run(sink).await;
    });

    let sender = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
    sender.send_to(b"hits:1|c", addr).await.expect("send should reach statsd_in");
    sender.send_to(b"hits:1|c", addr).await.expect("send should reach statsd_in");

    let mut aggregator = Aggregator::new(Duration::from_secs(3600))
        .with_temporality(AggregateTemporality::Cumulative)
        .with_series_retention(5, 10_000);

    // `UdpListenerConfig::default`'s `batch_flush_interval` (100ms) may coalesce both datagrams
    // into a single batch rather than delivering one per send, so this collects events (not
    // batches) until both increments have arrived, rather than assuming a 1:1 batch:datagram
    // correspondence.
    let mut absorbed_events = 0;
    while absorbed_events < 2 {
        let delivered = tokio::time::timeout(Duration::from_secs(2), rx.recv())
            .await
            .expect("statsd_in should forward both increments")
            .expect("the Fanout channel should not have closed");
        let batch = logit_pipeline::unwrap_batch(delivered);
        let resource = batch.resource.clone();
        for event in batch.events {
            absorbed_events += 1;
            let absorbed = aggregator.process(&resource, event);
            assert!(
                absorbed.is_none(),
                "a delta Sum under cumulative temporality must be absorbed"
            );
        }
    }

    let flushed = aggregator.flush(1_700_000_000_000_000_000);
    assert!(!flushed.is_empty(), "two absorbed increments must produce a flushed batch");
    let batches: Vec<EventBatch> = flushed
        .into_iter()
        .map(|(resource, scope, events)| EventBatch {
            resource,
            scope,
            events: events.into_iter().map(|(event, _links)| event).collect(),
        })
        .collect();

    let (body, _addr) = expose_and_fetch(&batches, ACCEPT_OM).await;
    assert!(
        body.contains("hits_total 2"),
        "expected a cumulative hits_total 2 sample, got:\n{body}"
    );
    assert!(
        body.contains("hits_created"),
        "temporality: cumulative sets start_timestamp, which prometheus_out renders as \
         _created in OpenMetrics; got:\n{body}"
    );
}

/// `internal -> aggregate(temporality: cumulative) -> prometheus_out`: `logit`'s own self-telemetry
/// (an ordinary `logit.component.*` counter, drained by `internal` like any other component's) still
/// renders as an ordinary counter family -- proving `prometheus_out` is fed by the graph like any
/// other sink, not a second telemetry representation, per
/// [ADR `internal-telemetry-as-pipeline-events`](../../../docs/adr/internal-telemetry-as-pipeline-events.md)'s
/// amendment.
#[tokio::test]
async fn internal_telemetry_through_cumulative_aggregate_renders_a_logit_component_counter() {
    let registry = Registry::new();
    let telemetry = registry.telemetry_for("probe", "statsd_in", "listener");
    telemetry.count("logit.component.batches.sent", 3.0, &[]);

    let mut input = InternalInput::new(Duration::from_millis(20), registry);
    let (tx, mut rx) = mpsc::channel(16);
    let sink = Fanout::new(vec![tx]);
    tokio::spawn(async move {
        let _ = input.run(sink).await;
    });

    let delivered = tokio::time::timeout(Duration::from_secs(2), rx.recv())
        .await
        .expect("internal should drain and forward a batch")
        .expect("the Fanout channel should not have closed");
    let batch = logit_pipeline::unwrap_batch(delivered);

    let mut aggregator = Aggregator::new(Duration::from_secs(3600))
        .with_temporality(AggregateTemporality::Cumulative)
        .with_series_retention(5, 10_000);

    let mut passthrough = Vec::new();
    for event in batch.events {
        if let Some(forwarded) = aggregator.process(&batch.resource, event) {
            passthrough.push(forwarded);
        }
    }

    let flushed = aggregator.flush(1_700_000_000_000_000_000);
    let mut batches: Vec<EventBatch> = flushed
        .into_iter()
        .map(|(resource, scope, events)| EventBatch {
            resource,
            scope,
            events: events.into_iter().map(|(event, _links)| event).collect(),
        })
        .collect();
    if !passthrough.is_empty() {
        batches.push(EventBatch {
            resource: batch.resource.clone(),
            scope: batch.scope.clone(),
            events: passthrough,
        });
    }

    let (body, _addr) = expose_and_fetch(&batches, ACCEPT_TEXT).await;
    assert!(
        body.contains("logit_component_batches_sent_total"),
        "expected at least one logit_component_* counter family, got:\n{body}"
    );
}
