[package]
name = "logit-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "The logit binary."

[[bin]]
name = "logit"
path = "src/main.rs"

[dependencies]
logit-config.workspace = true
logit-core.workspace = true
logit-inputs.workspace = true
logit-outputs.workspace = true
logit-script.workspace = true
clap.workspace = true
serde_json.workspace = true
serde_norway.workspace = true
anyhow.workspace = true
tokio.workspace = true
